whitequark/parser

- README.md
- parser.gemspec
This pull request updates the parser gemspec metadata to use an encrypted HTTPS URL for the gem's homepage.
It also updates the README to use encrypted connections to sites that support HTTPS (GitHub, RubyGems, etc)
> use HTTPS URLs in gemspec and README

- lib/parser/source/comment.rb
- lib/parser/source/comment/associator.rb
- test/test_source_comment_associator.rb
This PR makes the "Comment Associator" behave differently to solve 2 issues and allow callers to make the difference between "heading" comments, which come before a piece of code, and "decorative" comments which come right after the code they are associated to.
Changes:
- associator#associate now returns 2 hashes: @commentMap and @decorative_comment
- @commentMap corresponds to the hash which the function used to return, but with a different key to fix the issue of "merged" comments for similar nodes (issue #184). The key is now the node's location instead of the node itself (the value is an array of comments, this did not change).
- The new returned hash @decorative_comment uses the comment as key. The value is a boolean which is true if the comment is "decorative" (false for heading …
> * Changed Comment::Associator#associate API and way of associating comments

- lib/parser/source/buffer.rb
I was running some memory profiles on RuboCop and noticed that the highest memory allocation was coming from `parser-2.2.2.5/lib/parser/source/buffer.rb`. This change reduces the memory allocation by about 30%.
> Reduce object count

- lib/parser/ast/processor.rb
I'm not sure if there is a good reason for these methods to exist, but I sure can't see any. Removing the unneeded indirection should increase performance a little bit.
I've checked RuboCop and it doesn't use the removed methods.
> Remove unneeded indirection in Parser::AST::Processor

- lib/parser/lexer.rl
```
```
This patch reduce Kernel#class method call on Parser::Lexcer#advance.
Method call changes from 446708 calls to 71174 calls.
Total time changes from 0.401 ms to 0.22 ms.
That reduce Parser::Lexer#advance total time 36.697 to 36.520
Result detail is followings:
```
Thread ID: 2225978120                                                                   Thread ID: 2225978120
Fiber ID: 2229069920                                                                    Fiber ID: 2229069920 …
```
> * lexer.rl: reduce .class method call on #advance

- lib/parser/lexer.rl
```
```
This patch reduce String#length method call on Parser::Lexcer#advance.
Method call changes from 76473 calls to 38898 calls.
Total time changes from 0.616 ms to 0.303 ms.
Result detail is followings:
```
Thread ID: 2225978120                                                               |   Thread ID: 2280504080
Fiber ID: 2229069920                                                                |   Fiber ID: 2283604480
Total: 38.818560 …
```
> * lexer.rl: reduce Stirng.length method call on #advance

- lib/parser/lexer.rl
```
```
This patch reduce respond_to?(:encode) method call on Parser::Lexcer#advance.
String#encode can detect statically.
Method call changes from 88830 calls to 1417 calls.
Total time changes from 0.099 ms to 0.002 ms.
Result detail is followings:
```
Thread ID: 2225978120                                                               |   Thread ID: 2196618000
Fiber ID: 2229069920                                                                |   Fiber ID: 2199718400
Total: 38.818560 …
```
> * lexer.rl: reduce respond_to?(:encode) method call on #advance

- lib/parser/source/buffer.rb
```
$ time ruby-prof -f before_rubocop  ./bin/ruby-rubocop -- --cache false test/**/*.rb
$ time ruby-prof -f after_rubocop  ./bin/ruby-rubocop -- --cache false test/**/*.rb
$ diff -W 170 -y before-rubocop after-rubocop | less
```
bin/ruby-rubocop is followings:
```
#!/usr/bin/env ruby
$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__))
require 'parser'
require 'rubocop'
require 'benchmark'
cli = RuboCop::CLI.new
result = 0
time = Benchmark.realtime do
result = cli.run
end
puts "Finished in #{time} seconds" if cli.options[:debug]
exit result
```
This patch reduce respond_to? calls from 5172087 to 4541354.
and total time reduce 2.620 to 2.439.
```
Thread ID: 2184094160 …
```
> * lib/parser/source/buffer: reduce respond_to?(:bsearch)

- lib/parser/lexer.rl
This patch reduce String literal object allocations.
String object expanded many times on Lexer#advance.
> * lexer.rl: reduce String literal object allocations

- lib/parser/lexer.rl
in #220, I found more allocation points.
```
diff --git bin/ruby-parse bin/ruby-parse
index e55c2f4..7f34f91 100755
--- bin/ruby-parse
+++ bin/ruby-parse
@@ -3,4 +3,14 @@
$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__))
require 'parser/runner/ruby_parse'
+require 'pp'
+require 'allocation_tracer'
+
+trace_result = ObjectSpace::AllocationTracer.trace{
Parser::Runner::RubyParse.go(ARGV)
+}.select {|key| key[0].include?('parser/lexer.rb') }
+.each_with_object({}) {|(key,val),j| j[key] = val[0] }
+trace_result.sort_by {|key,val| key[1] }.each do |key,val|
+  puts "#{key[0]}:#{key[1]} :#{val}"
+end
+p trace_result.inject(0) {|sum,(key,val)| sum += val; sum }
```
and
BEFORE: 601599
AFTER: 590269
> lexer.rl: reduce Array literal object allocations

- lib/parser/lexer.rl
```
```
This patch reduce String#encode calls from 133957 times to 1 times if encoding is same.
total time changes 0.298 to 0.00.
```
Thread ID: 2280563160                                                               |   Thread ID: 2272174560
Fiber ID: 2282587940                                                                |   Fiber ID: 2272047580
Total: 39.815373                                                                    |   Total: 39.309657
Sort by: self_time …
```
> lexer.rl: recude encode method calls if not need

- lib/parser/lexer.rl
```
```
Lexer#literal can be cached before calling Lexer#pop_literal
This patch reduce literal method call from 132825 times to 45291 times.
Time changed from 0.283 ms to 0.096
And also changed Array#last method calls from 134027 times to 46493.
Time changed from 0.118 ms to 0.051.
```
Thread ID: 2280563160                                                               |   Thread ID: 2211357140
Fiber ID: 2282587940                                                                |   Fiber …
```
> lexer.rl: reduce literal method calls

- Rakefile
- lib/parser/lexer.rl
I tried to use ruby 2.3.0-preview1 feature "frozen_string_literal: true".
It does not improve performance now.
But generated lexer.rb include some string literal. and it may affect some performance improvement in future.
BEFORE
```
run "ruby bin/ruby-parse test/*.rb"
4.161907772s
4.07406064s
4.034552265s
4.153820199s
4.07035989s
4.047238321s
4.077487832s
3.979082707s
4.025522643s
3.98664261s
count:  10 times executed
avg:    4.061067487s
stdev:  55.362386ms
```
AFTER
```
run "ruby bin/ruby-parse test/*.rb"
4.030414207s
4.256804907s
4.215693019s
4.032238326s
4.045159886s
3.982182805s
4.015422779s
3.998105521s
4.054807781s
4.045414991s
count:  10 times executed
avg:    4.067624422s
stdev:  83.323401ms
```
> support enable fronzen_string_literal for over ruby 2.3.0

- Gemfile
- Rakefile
- lib/parser/diagnostic.rb
- lib/parser/source/buffer.rb
- lib/parser/source/range.rb
- lib/parser/source/rewriter.rb
- test/test_diagnostic.rb
- test/test_source_buffer.rb
- test/test_source_range.rb
- test/test_source_rewriter.rb
I just ran into a couple problems when working on some RuboCop code which prompted me to make these enhancements.
It started with a RC cop which deletes some unneeded things. In some circumstances, it may try to autocorrect overlapping ranges of code. This causes `parser` to vomit up a `ClobberingError`.
The thing is that there is no conflict at all between the overlapping edits. They are just all deleting code anyways. So this PR amends `Rewriter` so that it is smart enough to notice when there is no conflict between overlapping deletions *or* replacements, and merge them when possible.
Another thing: some of those deletions span newlines. So at first, I couldn't even see that the problem was a `ClobberingError`, because `Diagnostic#render` calls `column_range`, and that fails if the …
> Enhance Range and Rewriter

- lib/parser/source/buffer.rb
- test/test_source_buffer.rb
Buffer already has `#first_line`. `#last_line` is symmetrical with
`#first_line`, and will be generally useful. (Specifically, it will be helpful
with some work I am doing on RuboCop.)
> Add Source::Buffer#last_line

- lib/parser/source/buffer.rb
- test/test_source_buffer.rb
@whitequark Please have a look at this and see if you want it. Commit log message:
Almost any application which processes Ruby source code will want to access
specific lines. `Buffer#source_line` is provided for that purpose; however,
sometimes one wants an `Enumerable` object, which `#map`, `#select`, and so
on can be called on.
`Parser::Source::Buffer` already maintains such an array, but it wasn't exposed.
This caused RuboCop to maintain its own array of lines for each `Buffer`,
at a not-insignificant performance cost.
Exposing the `@lines` array to client code means that it and its contents must
all be frozen to prevent unwanted mutation. This means that accessing source
lines using `#lines` is more efficient than `#source_line`, since there is no
extra copying.
> Add Source::Buffer#lines

- lib/parser/lexer.rl
I was just reading some code, and noticed what seemed to be an unneeded copy operation here. Am I right? Is there some other reason why this code is needed?
To retrieve a codepoint, we have:
```
getkey (@source_pts[p] || 0);
```
...So the lexer will retrieve a zero at EOF anyways.
> Avoid copying content of input source buffer

- lib/parser/lexer.rl
In a number of cases, a table lookup is used to find the token to emit, although
there is only one possible token which could be emitted from that point. It
makes the code clearer when the reader can see the token which will be emitted,
rather than having to go and consult the table.
> Simplify lexer code which unnecessarily uses emit_table

- lib/parser/lexer.rl
- lib/parser/lexer/literal.rb
- test/test_lexer.rb
Hey, @whitequark, please check and see if I'm totally off base here.
If I am right about this, then I think the only reason to store error lambdas in `@escape` rather than just calling `diagnostic` directly has just disappeared.
> Ruby has no such thing as backslash-delimited strings

- lib/parser/meta.rb
Also fixes a duplicate `send` member.
> - Add :csend to Parser::Meta::NODE_TYPES

- lib/parser/source/buffer.rb
The existing code uses `String#each_char`, which allocates a new string object for **each** character in the source file. (This is the #2 source of object allocations in RuboCop.) It also uses a lot of (slow) Ruby method calls.
Switching to `String#index` increases the performance of `Source::Buffer#line_begins` by a factor of more than 20.
> Make Buffer#line_begins fly

- lib/parser/source/rewriter.rb
- test/test_source_rewriter.rb
Previously, insertions ("replacements" of a zero-length range) would never
clobber or be clobbered by anything, even if they landed right in the middle
of a replaced or deleted range of text. As can easily be seen, this makes a
mess and should give rise to a clobbering error.
The tricky thing is that an insertion can legitimately appear at the very
beginning or very end of a replaced or deleted range. If it is in the middle,
though, that is definitely wrong and should cause an error. (Unless it appears
in the middle of a replaced range, and the replacement is longer than the
replaced text by the length of the insertion or more, and the replacement has
the same effect as the insertion.)
Additionally, two insertions at the very same point should also clobber each
other. Why? Well, how do we …
> Source::Rewriter handles clobbering correctly for insertions

- lib/parser/lexer.rl
Sorry and thanks for pointing out my mistake!
bb0f0e6 modified the lexer in one place to build a string using `String#<<` on
a string literal. Since lexer.rb includes a `frozen_string_literal: true`
comment, this would fail on MRI 2.3.
> Fix broken build on MRI 2.3

- lib/parser/lexer.rl
- test/test_lexer.rb
When working on optimization of `Range#line`, I looked at what tests we have for ranges emitted by the lexer and was surprised to discover that the test suite hardly checks anything at all as re: correctness of the lexed ranges.
Perhaps unsurprisingly, when I tightened the test suite up to check the begin and end of each emitted range, it led me to discover a (relatively minor) bug.
@whitequark, see if you like the way the ranges are tested here or if you would prefer something else.
> Test emitted ranges

- lib/parser/source/buffer.rb
- lib/parser/source/range.rb
This halves the time which RuboCop spends in `Range#line`.
...Which will probably not be enough, eventually. But for now, it's good. That's why I annotated the added methods as `@api private` -- we may come up with something better later.
(It turns out that tracking the line numbers in the lexer is even more difficult than I thought. The handling of newlines would have to be completely reworked, and I have better things to work on.)
Closes #260.
> Cache line/column numbers for fast lookup in Source::Buffer

- lib/parser/lexer.rl
- test/parse_helper.rb
In one of my other PRs, @whitequark suggested that the parser tests should be run with the `force_utf32` flag set on the lexer. This amends the test suite to do just that; actually, it runs the parser tests both with and without `force_utf32`.
This immediately revealed that some of my optimizations to avoid string allocations were not sound, as @whitequark earlier said. The ones which break the test suite have been backed out.
Additionally, another bug was revealed: parsing escapes can break the lexer when `force_utf32` is on. The reason is that hash lookup in `ESCAPES` doesn't work when the source has been transcoded to UTF-32LE, because the keys of `ESCAPES` are not in that encoding. Then `ESCAPES.fetch(char, char)` returns the escaped char (which could be `"n"` or anything else), and …
> Testing UTF-32LE

- lib/parser/lexer.rl
- test/test_lexer.rb
If the input contains high-bit codepoints, always transcode to UTF-32,
to ensure O(1) string slicing. This prevents quadratic behavior, because
string indexing and slicing is O(n) on UTF-8-encoded strings. (An
internal Ruby optimization preserves constant-time access if the string
is UTF-8-encoded but happes to only contain ASCII characters.
fixes #268
> Improve performance parsing non-ASCII input.

- lib/parser/lexer.rl
- lib/parser/lexer/literal.rb
- lib/parser/source/buffer.rb
- lib/parser/source/range.rb
- test/test_lexer.rb
@whitequark how do you feel about this, or something like this? The last
PR essentially fixed the parser performance, but rubocop was still slow
becaue of repeated slicing of source ranges. I don't have an intuition
for whether the extra cost of indirecting through @source_buffer is too
expensive -- I realize the lexer is some of the hottest code here.
---
This is an attempt to generalize the performance gains of #269 to extend
to clients of the resulting AST.
The immediate problem is that many AST consumers (rubocop is the one I'm
currently interested in) are going to invoke
`Parser::Source::Range#source` on many of the AST nodes, and that method
has the same linear-time-slicing behavior as `Parser::Lexer#tok` did.
By pushing the re-encoding inside the `Parser::Source::Buffer` …
> Generalize the unicode performance fixes.

- lib/parser/source/rewriter.rb
- test/test_source_rewriter.rb
Just found a bug in my `Rewriter` code while working on RuboCop...
Sorry @whitequark!
> Merging of replace actions in Source::Rewriter produces correct replaced range

- .gitignore
- Rakefile
Required for https://github.com/opal/opal/pull/1465
> Pass --no-line-convert to Racc to prevent wrapping generated parser code with module_eval.

- lib/parser/macruby.y
- lib/parser/ruby19.y
- lib/parser/ruby20.y
- lib/parser/ruby21.y
- lib/parser/ruby22.y
- lib/parser/ruby23.y
- lib/parser/ruby24.y
- lib/parser/rubymotion.y
- test/test_parser.rb
``` sh
ruby-parse -e "lambda{|;a|a}"
```
Before:
```
(block
(send nil :lambda)
(args
(shadowarg :a))
(send nil :a))
```
After:
```
(block
(send nil :lambda)
(args
(shadowarg :a))
(lvar :a))
```
> Treat shadowarg as local variable inside the block.

- lib/parser/current.rb
https://www.ruby-lang.org/en/news/2016/04/26/ruby-2-2-5-released/
> * parser/current: update 2.2 warning to 2.2.5

- lib/parser/lexer.rl
- test/test_lexer.rb
Problem
======
parser crashes when parsing words are delimited by backslash.
e.g.
```sh
$ ruby-parse --version
ruby-parse based on parser version 2.3.1.2
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
$ echo -E -n '%w\a b\' > without_nl.rb
$ ruby -c without_nl.rb
Syntax OK
$ ruby-parse without_nl.rb  # This works
(array
(str "a")
(str "b"))
$ echo -E  '%w\a b\' > with_nl.rb
$ ruby -c with_nl.rb 
Syntax OK
$ with_nl.rb:1:1: fatal: unterminated string meets end of file
with_nl.rb:1: %w\a b\
with_nl.rb:1: ^      
```
> - Fix parsing words are delimited by backslash. e.g.) `%w\a b\`

- lib/parser/ast/processor.rb
> - Parser::AST::Processor: do not add nil to the end of required argument.

- .travis.yml
I've extracted this from #313 which was experiencing failures for all MRI ruby versions due to the old rubygems version. This change should fix the problem and also make it possible to move 1.9.3 out of `allowed_failures`.
> Update rubygems version in .travis.yml

- lib/parser/macruby.y
- lib/parser/ruby18.y
- lib/parser/ruby19.y
- lib/parser/ruby20.y
- lib/parser/ruby21.y
- lib/parser/ruby22.y
- lib/parser/ruby23.y
- lib/parser/ruby24.y
- lib/parser/rubymotion.y
- test/test_parser.rb
Fixes #312 and backports the parser change to all rubies including 1.8, ruby motion, and macruby. I installed 1.8 and verified that this syntax should be backported that far. I was also able to verify this syntax for macruby but I'm not sure how to install rubymotion.
> Fix mlhs for block arguments with trailing commas

- lib/parser/current.rb
Ruby 2.3.3 was released to patch a regression found in 2.3.2.
> * parser/current: update 2.3 branch to 2.3.3.

- lib/parser/current.rb
https://www.ruby-lang.org/en/news/2016/11/15/ruby-2-2-6-released/
> * parser/current: update 2.2 warning to 2.2.6

- doc/AST_FORMAT.md
Without the blank line, the markup is broken.
> Fix ruby_parser comparison markup

- lib/parser/meta.rb
A trivial change. I referenced this list while working on something in RuboCop, and I noticed some of the node types are duplicated.
It doesn't have a practical impact since duplicates are removed as the `Array` is coerced into a `Set`, but it's nice to have the list in its normalised form.
> Remove duplicate node declarations in `Meta::NODE_TYPES`

- lib/parser/builders/default.rb
- test/test_parser.rb
Commit c1310f6 introduces a new behavior that got merged for the Ruby
2.4 release: multi-asgn is now allowed in a conditional context.
Besides the changes to the language grammar, the commit also updates the
AST builder (builder/default.rb @ check_condition) to stop it from
emiting a diagnostic error in 2.4.
This change, however, is not correct: the condition check for Ruby 2.4
does not emit an error anymore, but it does not return the AST nodes it
was checking either. Without an explicit return, the `:masgn` branch of
the function yields a `nil`, swallowing up the expressions inside the
condition of the `if` statement.
The fix is trivial: return the value we were checking. The corresponding
test has been updated to reflect the change -- the previous AST output
was missing all the …
> ruby24: Generate proper AST for multi-asgn in condition

- test/test_source_map.rb
Found a misnamed test class when I was looking around. This change fixes that.
> Correct misnamed `TestSourceMap` class

- .travis.yml
- lib/parser/source/rewriter.rb
- test/parse_helper.rb
- test/test_base.rb
- test/test_encoding.rb
- test/test_parse_helper.rb
- test/test_parser.rb
1. Fixed warnings in `Parser::Source::Rewriter`.
2. Fixed warnings coming from minitest (`assert nil, value` -> `assert_nil value`, see https://github.com/seattlerb/minitest/issues/666)
3. Changed CI config, it can fix an issue with installing 1.9.2 on Travis.
> Fix warnings

- lib/parser/current.rb
Follow up of https://github.com/whitequark/parser/pull/362#issuecomment-325368370.
Currently, it seems there are no open issues for Ruby 2.1 and 2.2. This PR updates them.
> Parser::Current: update for Ruby 2.1.10 and 2.2.7

- Rakefile
Bundler does not require `date` after 1.14.4.
https://github.com/bundler/bundler/issues/5470
So `rake changelog` task does not work with new bundler. This change will fix this problem.
> Add `require 'date'` into Rakefile

- lib/parser/lexer/literal.rb
`+=` is replaced with `<<` in `extend_string` method in #293.
This replacing did not introduce performance regressions about small string. However, it has introduced a performance regression about a string that contains very long line.
This seems to be a problem in an actual application. An issue was opened
in RuboCop repository about this problem. https://github.com/bbatsov/rubocop/issues/4701
`<<` is replaced with `+=` also in `initialize` method by #293. However this `<<` doesn't introduce regressions because it is a concatenation of small strings.
Benchmark
-----
```
File.open 'test.rb', 'w' do |f|
f.write '"'
f.write 'a' * 100000
f.write '"'
end
```
Master:
```bash
$ bin/ruby-parse -B test.rb
Parsed 1 files (100002 characters) in 0.73 seconds (136.989 kchars/s).
Running on ruby …
```
> Fix performance regression for a string that contains a very long line

- lib/parser/current.rb
Ruby 2.2.8 has been released.
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-2-8-released/
As far as I saw, there seems to be no change in syntax to `parse.y` etc.
https://github.com/ruby/ruby/compare/v2_2_7...v2_2_8
> Parser::Current: update for Ruby 2.2.8

- .travis.yml
This PR tries to make the CI a little more efficient.
- rvm nowadays update rubygems on its own, at install of a Ruby
- `gem install bundler` will install latest (_and_ if the version of Ruby does not ship with a Bundler, such as perhaps jruby-head, for example, the update command may fail)
> Travis: skip extra gem update --system

- .travis.yml
- test/racc_coverage_helper.rb
~Racc has issues building in jruby-18mode, jruby-19mode~
~To allow the CI to remain useful until those issues can be... resolved, this PR places those platforms in `allow_failures`.~
**Update**: Renamed PR to match content.
> Travis: Use JRuby 9.1.13.0, add 2.4.0

- lib/parser/builders/default.rb
- test/test_parser.rb
Problem
===
MRI's parser treats the body of `not` as a condition.
For example:
```bash
$ ruby -ce '!(a, b = x)'
-e:1 multiple assignment in conditional
$ ruby -ce '!(a,b=x)'
Syntax OK
$ ruby -e '$_ = "a"; p(!(/a/)); p(!(/b/))'
false
true
$ ruby -e 'x = 0; p !((x==1)..(x==2))'
true
$ ruby -e 'x = 1; p !((x==1)..(x==2))'
false
```
But parser gem does not treat body of `not` as a condition.
For example:
```ruby
$ ruby-parse --23 -e '!(a, b = x)'
(send
(begin
(masgn
(mlhs
(lvasgn :a)
(lvasgn :b))
(send nil :x))) :!)
$ ruby-parse -e '!/a/'
(send
(regexp
(str "a")
(regopt)) :!)
$ ruby-parse -e '!(a..b)'
(send
(begin
(irange
(send nil :a)
(send nil :b))) :!)
```
Solution
------
Apply `check_condition` method for `not_op`.
By this change, all above problems are resolved.
> Use `check_condition` for `not` node

- test/test_lexer.rb
`test_do_cond` and `test_identifier_eh` is redefined.
With `RUBYOPT=-w`, `rake` command displays the following warnings.
```
/home/pocke/ghq/github.com/whitequark/parser/test/test_lexer.rb:591: warning: method redefined; discarding old test_do_cond
/home/pocke/ghq/github.com/whitequark/parser/test/test_lexer.rb:572: warning: previous definition of test_do_cond was here
/home/pocke/ghq/github.com/whitequark/parser/test/test_lexer.rb:981: warning: method redefined; discarding old test_identifier_eh
/home/pocke/ghq/github.com/whitequark/parser/test/test_lexer.rb:964: warning: previous definition of test_identifier_eh was here
```
This change only suppresses one of the warnings that is for `test_do_cond`.
`test_do_cond` is defined twice with same meaning code.
So, we can remove one of these …
> Remove a duplicated test

- Rakefile
The 'generate' Rake task runs every time the tests are run, YARD documentation is
generated, and so on. Even if all the generated files are already there, it adds another
encoding comment to them each time. If you repeatedly run the tests while working on the
Parser codebase, these generated files accumulate more and more encoding comments at the
top.
Put an end to this silliness by only adding the encoding comment if it is not already there.
> Don't add dozens of encoding comments to each generated file

- lib/parser/source/comment/associator.rb
- test/test_source_comment_associator.rb
This makes the comment associator ignore the following magic comments:
* `frozen_string_literal`
* `warn_indent`
* `warn_past_scope`
Fixes #386.
Questions:
* `MAGIC_COMMENT_RE` and `Buffer::ENCODING_RE` are very similar. I’d prefer for them to be combined somehow, but I can’t think of a good way to do it. Might it make sense to move `MAGIC_COMMENT_RE` into `Buffer`, at least?
* `warn_past_scope` is only activated when `WARN_PAST_SCOPE` is set when compiling Ruby (it isn’t by default). Given that, does it still make sense to support it?
> Skip magic comments

- lib/parser/source/comment/associator.rb
String#start_with? is faster than Regex match If it does not need Regexp match.
> use String#start_with? instread of Regexp match

- lib/parser/ruby25.y
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/337
> Allow rescue/else/ensure inside do/end blocks. [Feature #12906]

- lib/parser/lexer.rl
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/347
@whitequark Is it possible to move it to `ruby24.y/ruby25.y`?
> Allow do after cmdarg in paren.

- lib/parser/lexer.rl
- lib/parser/messages.rb
- test/test_lexer.rb
Closes https://github.com/whitequark/parser/issues/334
> Allow newlines in heredoc identifiers.

- lib/parser/source/rewriter.rb
- test/test_source_rewriter.rb
While the order of multiple calls to either `insert_after_multi` or `insert_before_multi` is well tested and documented, the relative order of `insert_after_multi` and `insert_before_multi` done at the same point isn't.
My use case is I wanted to rewrite:
```
foo.bar
```
into:
```
<span class="...">foo</span><span>.</span><span ...>bar</span>
```
To do so, I inserted my opening tags before each range, and my closing tags after. This gives me the wrong result! I'd have to insert my opening tags using `insert_after` and my closing tags using `insert_before`!
This PR fixes it by prioritizing `insert_after` over `insert_before`. This is a potentially breaking change, but neither the doc nor the tests condone the current behavior. 
Implementation isn't super pretty, but I favored it over …
> Change relative order of insert_after_multi and insert_before_multi

- lib/parser/lexer.rl
- test/test_lexer.rb
Closes https://github.com/whitequark/parser/issues/330.
This is my first contribution to lexer, so I need some help:
1. ~~There's 1 failing spec - `"\u{}"` should produce an error, there's an explicit machine (line 738) that handles it, but for some reason ragel doesn't enter it (I'm still reading ragel guide, so I guess I simply don't understand something). This rule is on top of all `u{` rules, and it matches a string content completely. Ragel emits an unescaped string.~~
2. Is there some style guide for ragel syntax? I've tried to write rules using existing code style, is it ok?
3. Also I have a feeling that probably it makes sense to extract parts related to whitespace handling to separate machines (something like `optional_surrounding_spaces_in_unicode_codepoints` / …
> Relax restriction spaces inside "\u{...}".

- lib/parser/lexer/stack_state.rb
Closes https://github.com/whitequark/parser/issues/398.
By the way, not sure what should be returned from `lexpop`. That's basically a void procedure and the code that invokes it never uses its return value. But there are some tests that actually use it for assertions, so I've changed the method to pass them. @whitequark Please, let me know if it's wrong and must be changed.
> Fix Parser::Lexer::StackState#lexpop to match MRI behavior.

- lib/parser/builders/default.rb
- lib/parser/diagnostic.rb
- lib/parser/source/range.rb
- test/test_source_range.rb
Whenever I work with ranges, I find that I'm always creating ranges from other ranges, tweaking either end points, sometimes both.
I'm proposing `Range#with` to easily update either or both end points.
This not only saves keystrokes, it makes it easier to read and see what is being changed.
I've used it 8 times in `parser` itself.
I'm counting about 20 uses in Rubocop (not counting the specs), plus eliminating [`slice_source`](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/format_string_token.rb#L126-L132) which it makes redundant.
PS: I was waiting for Ruby 1.9 support to die, but this version can do until then.
> + Add Range#with. Use it where convenient

- lib/parser/source/range.rb
- test/test_source_range.rb
This first fixes the edge case for equal and empty ranges for `disjoint?`, `overlaps?` and `intersect`.
Then, it adds `contains?`, `contained?` and `crossing?`, in such a way that any two ranges are one and only one of `==`, `disjoint?`, `contains?`, `contained?` or `crossing?
*Note*: Dealing with "empty" ranges can be confusing. I find it helps a lot to translate Range(1, 4) to 1..3 and Range(4, 4) to 3.5
At first I was thinking of them as actually empty; nothing was working and my head was close to exploding.
(This is a prelude to my `TreeRewriter` PR)
> Range relationship

- lib/parser/source/range.rb
- test/test_source_range.rb
I'm not proud to admit I screwed up the corner case for empty ranges & `disjoint?`. I was actually missing a few tests too, which this completes.
> Fix disjoint? for empty & different ranges. Add tests.

- lib/parser/ruby24.y
- lib/parser/ruby25.y
- test/test_parser.rb
Ports commit b4aa884f06ee5c40f88e90f312ea6b31c120f308 from
github.com/ruby/ruby:
* parse.y (do_body): preserve cmdarg stack around do/end block.
[ruby-core:78837] [Bug #13073]
> Fix parse error when hash contains do blocks

- lib/parser/lexer.rl
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/367
ruby/ruby@50f7d64.
> Disable tLPAREN_ARG state by local variable.

- parser.gemspec
`required_ruby_version` is missing from the gemspec.
> Add the required Ruby version to gemspec

- .travis.yml
- lib/parser/current.rb
See https://www.ruby-lang.org/en/downloads/releases/
> Bump latest Ruby versions

- lib/parser/lexer.rl
- test/test_lexer.rb
Closes https://github.com/whitequark/parser/issues/423
> Emit :&& as tSYMBEG + tANDOP, :|| as tSYMBEG + tOROP.

- lib/parser/lexer.rl
- test/test_lexer.rb
> Save state before entering a block comment to enter it after =end.

- .travis.yml
ruby 2.5.0 was released. https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/
update 2.4.x to edge version https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-4-3-released/
update jruby version http://jruby.org/2017/12/07/jruby-9-1-15-0.html
> update .travis.yml to running test with ruby 2.4.3 and ruby 2.5.0

- lib/parser/source/buffer.rb
- test/test_encoding.rb
Closes https://github.com/whitequark/parser/issues/443
> Fixed magic encoding comment parsing when encoding comment is on the first line but not in the beginning.

- lib/parser/lexer.rl
- lib/parser/ruby24.y
- lib/parser/ruby25.y
- test/parse_helper.rb
- test/test_parser.rb
Hopefully closes https://github.com/whitequark/parser/issues/359
@whitequark A couple of questions:
1. Do you see any other cases that need to be tested?
2. This behavior is common for all ruby versions (tests pass when I change `SINCE_2_4` to `ALL_VERSIONS`) and I don't see any similar tests for older versions of parser. Should I put `ALL_VERSIONS` to these tests?
> Reject brace after literal arg.

- lib/parser/ruby25.y
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/429
ruby/ruby@9d9d87f.
> ruby25: Allow `-> do rescue; end`.

- lib/parser/ruby25.y
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/430.
ruby/ruby@0dfec65 and ruby/ruby@5aa3523.
MRI doesn't have test cases for singleton method definition and singleton class handling in the while condition but in fact it handles it well (there are changes in corresponding sections in MRI's `parse.y`):
``` sh
$ dev-ruby -vce 'while def self.foo; tap do end; end; break; end;'
ruby 2.6.0dev (2018-01-10 trunk 61758) [x86_64-darwin17]
Syntax OK
$ dev-ruby -vce 'while class << self; tap do end; end; break; end'
ruby 2.6.0dev (2018-01-10 trunk 61758) [x86_64-darwin17]
Syntax OK
```
> ruby25.y: Allow class and method definition in the while condition.

- lib/parser/lexer.rl
- lib/parser/ruby24.y
- lib/parser/ruby25.y
- test/test_parser.rb
Fixes https://github.com/whitequark/parser/issues/447
Closes https://github.com/whitequark/parser/issues/433
From what I understand `command_args` rule always gets invoked in the lookahead, so inside this rule `last_token` always contains the first token of `command_args`. Bison has a `yychar` variable that is always equal to the last lookahead token (for this case `last_token` can handle it). Is there a similar thing in racc?
> Fixed cmdarg manipulation in command_args rule.

- lib/parser/source/buffer.rb
- test/test_encoding.rb
Ruby ❤️ 
``` sh
$ cat test.rb
puts "".encoding
$ ruby test.rb
KOI8-R
```
I've checked other tests on MRI, the only difference is BOM meta-chars handling. MRI doesn't care about them. @whitequark Should we drop if from the parser as well?
> Fixed encoding comment handling.

- lib/parser/lexer.rl
- test/test_parser.rb
The bug is caused by `p -=` and thus calling action attached to `e_lbrace` twice. This patch removes lookahead and emits the token instantly to guarantee that the action of `e_lbrace` gets called only once.
Basically, lambda-branch in the modified action is replaced to what corresponding action does later in
```
expr_end := |*
e_lbrace | 'do'
=> {
if @lambda_stack.last == @paren_nest
@lambda_stack.pop
if tok == '{'.freeze
emit(:tLAMBEG, '{'.freeze)
else # 'do'
emit(:kDO_LAMBDA, 'do'.freeze)
end
else
if tok == '{'.freeze
emit(:tLCURLY, '{'.freeze)
else # 'do'
emit_do
end
end
fnext expr_value; fbreak;
};
*|;
```
Closes https://github.com/whitequark/parser/issues/435
> Fix parsing of interpolated lambda with open args.

- lib/parser/ruby24.y
- lib/parser/ruby25.y
- test/parse_helper.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@1727c83.
All other changes from this commit were initially ported from the `parser` (haha), so there's no need to backport them.
Closes https://github.com/whitequark/parser/issues/452
> Replicate cmdargs handling from MRI.

- lib/parser/lexer/literal.rb
- test/test_parser.rb
> call String#b instead of #dup+#force_encoding

- lib/parser/current.rb
Closes https://github.com/whitequark/parser/issues/454
> Bump warning message for 2.4.x branch in the parser/current.

- lib/parser/source/buffer.rb
- test/test_encoding.rb
My regression introduced in https://github.com/whitequark/parser/pull/444
> Fixed parsing of encoding comment when the file contains only shebang.

- lib/parser/source/rewriter.rb
- test/test_source_rewriter.rb
Fixes a mistake I made in the documentation (similarly in the name of a test method).
Sorry.
> Fix wording [ci-skip]

- lib/parser/source/tree_rewriter.rb
- test/test_source_tree_rewriter.rb
The error message was wrong and generated an error.
Very sorry about this.
> Fix Out of range error reporting

- lib/parser/source/buffer.rb
- test/test_source_buffer.rb
Minor tweak to make sure the 'name' argument is a string.
This has two advantages:
* One can pass a `Pathname`
* Avoid some strange parsing issues where the name is used by parser instead of `__FILE__`, generating unexpected ASTs (I had some `[:str, nil]` nodes which took created havoc with my type checking.
> Make sure Source::Buffer#name is a string

- lib/parser/lexer.rl
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/447
> Fix cmdarg handling for parsers < 24.

- test/test_source_tree_rewriter.rb
`test_multiple_actions` method is defined twice. So Ruby warns.
```
$ bundle exec rake
(snip)
/path/to/test/test_source_tree_rewriter.rb:138: warning: method redefined; discarding old test_multiple_actions
/path/to/test/test_source_tree_rewriter.rb:129: warning: previous definition of test_multiple_actions was here
(snip)
```
And they has exactly the same definition. So this change removes the one of them.
> Remove duplicate test case in test_source_tree_rewriter.rb

- lib/parser/lexer.rl
- test/test_parser.rb
`BEGIN` and `END` are correct as a method name.
But the parser does not accept them.
```
$ ruby -vce 'def BEGIN; end; def END; end'
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
Syntax OK
$ docker run --rm -it jonwood/ruby-1.8 ruby -vce 'def BEGIN; end; def END; end' 
ruby 1.8.7 (2013-06-27 MBARI 8/0x6770 on patchlevel 375) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2012.02
Syntax OK
```
We can confirm the results in other rubies from here. https://bacon-cannon.herokuapp.com/parmlinks/d34f5b5f-1573-4504-883c-3ab52f252381
```
$ ruby-parse -e 'def BEGIN; end; def END; end'
(fragment:0):1:5: error: unexpected token error
(fragment:0):1: def BEGIN; end; def END; end
(fragment:0):1:     ^~~~~
```
---
I'm not sure this patch is correct way. Can you help me?
- …
> - Accept `BEGIN` and `END` as correct method name

- lib/parser/ruby24.y
- lib/parser/ruby25.y
- test/test_parser.rb
Fixes #466.
By the way, now I think that there's a bug in MRI, `cmdarg.push(0)/pop` and `push/pop_cmdarg` are semantically equivalent if there's no garbage in the stack. Anyway, that's what MRI does in the [corresponding rule](https://github.com/ruby/ruby/blob/trunk/parse.y#L3579-L3606)
> Fix cmdarg handling around string interpolation.

- lib/parser/color.rb
- lib/parser/lexer/explanation.rb
- lib/parser/runner/ruby_parse.rb
> ruby-parse displays escape sequences only in tty

- lib/parser/base.rb
- lib/parser/lexer.rl
- lib/parser/ruby24.y
- lib/parser/ruby25.y
- test/test_parser.rb
Closes #473, see https://github.com/whitequark/parser/issues/473#issuecomment-374588226 for more information.
@whitequark The test actually verifies that `@cmdarg` is 0 after parsing (`assert_parses` does it in the end of its definition), please, let me know if it should be changed to the code from the reported issue to make an assertion explicit.
> Move last_token capturing from Lexer#emit to Parser#next_token.

- lib/parser/lexer.rl
- test/test_parser.rb
Also I've added missing `cmdarg_push` and `cond_push` for `{` in the string literal. MRI always does if, even if it's not important now (because of the `push_cmdarg`/`pop_cmdarg` around the string) - https://github.com/ruby/ruby/blob/trunk/parse.y#L8008-L8010
``` ruby
$ dev-ruby -ye '"#{}#{}#{}"' | grep "stack(pop)"
p->cond_stack(pop): 0 at line 8009
p->cmdarg_stack(pop): 0 at line 8010
p->cond_stack(pop): 0 at line 8009
p->cmdarg_stack(pop): 0 at line 8010
p->cond_stack(pop): 0 at line 8009
p->cmdarg_stack(pop): 0 at line 8010
```
Closes https://github.com/whitequark/parser/issues/480
@whitequark Does this bug mean that using `fcall` may be dangerous? Should we avoid it in the future?
> Emit tSTRING_BEG and tSTRING_DBEG one by one to allow parser to properly manipulate cmdarg stack

- lib/parser/lexer.rl
- test/test_lexer.rb
Closes https://github.com/whitequark/parser/issues/486
Any content after these magical chars is rejected:
```
2.5.0 :001 > :!@1
Traceback (most recent call last):
1: from /Users/ilya/.rvm/rubies/ruby-2.5.0/bin/irb:11:in `<main>'
SyntaxError ((irb):1: syntax error, unexpected tINTEGER, expecting end-of-input)
```
So instant transition to `expr_end` looks correct.
> Emit :!@ as :!, :~@ as :~.

- lib/parser/lexer.rl
I forgot about pushing this. It's related to my previous PR #457 but even though `value.b[0].ord` already would've been an improvement, `value.getbyte(0)` is even better.
> call String#getbyte

- lib/parser/current.rb
https://www.ruby-lang.org/en/downloads/
```
Stable releases:
Ruby 2.5.1
sha256: dac81822325b79c3ba9532b048c2123357d3310b2b40024202f360251d9829b1
Ruby 2.4.4
sha256: 254f1c1a79e4cc814d1e7320bc5bdd995dc57e08727d30a767664619a9c8ae5a
Ruby 2.3.7
sha256: 35cd349cddf78e4a0640d28ec8c7e88a2ae0db51ebd8926cd232bb70db2c7d7f
```
> Bump latest versions to 2.3.7, 2.4.4, 2.5.1.

- lib/parser/current.rb
I apologize, somehow missed it in https://github.com/whitequark/parser/pull/489
Closes https://github.com/whitequark/parser/issues/494
> Parser::Current: bump latest 2.2 branch to 2.2.10.

- lib/parser/lexer.rl
- test/test_parser.rb
MRI 2.4.4:
```
$ ruby -vce 'm {} {}'
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
-e:1: syntax error, unexpected { arg, expecting end-of-input
m {} {}
^
$ ruby -vce 'm [] {}'
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
Syntax OK
$ ruby -vce 'm a: {} {}'
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
Syntax OK
```
Parser 2.4:
```
$ bin/ruby-parse --24 -e 'm {} {}'
(fragment:0):1:6: error: unexpected token tLBRACE_ARG
(fragment:0):1: m {} {}
(fragment:0):1:      ^
$ bin/ruby-parse --24 -e 'm [] {}'
(block
(send nil :m
(array))
(args) nil)
$ bin/ruby-parse --24 -e 'm a: {} {}'
(block
(send nil :m
(hash
(pair
(sym :a)
(hash))))
(args) nil)
```
MRI 2.5.0
```
$ ruby -vce 'm {} {}'
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
-e:1: …
```
> Reject `m a: {} {}` and `m [] {}` since 25.

- lib/parser/lexer.rl
- test/test_lexer.rb
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/492
All operators in `operator_arithmetic` and `operator_rest` (except `|`, `~`, `!`) can be followed by quoted labels if this symbol is actually a string + tCOLON from the ternary operator.
> lexer.rl: Fix parsing of `a ? b + '': nil`.

- lib/parser/lexer.rl
- lib/parser/lexer/dedenter.rb
- lib/parser/lexer/literal.rb
- test/test_lexer.rb
- test/test_parser.rb
Upstream commits: ruby/ruby@491f523 and ruby/ruby@58fbe69.
Closes https://github.com/whitequark/parser/issues/479
The lexer must emit `"\\\n"` without escaping to let `Dedenter` know that there's a newline (and so that the code after must be dedented).
> Parse slash + newline in heredocs as a line continuation.

- lib/parser/lexer.rl
- lib/parser/lexer/stack_state.rb
- test/parse_helper.rb
- test/test_parser.rb
In this case lexer emits multiple tokens (`tLBRACE_ARG` + one more token because there's no `fbreak`) and `cmdarg.push` gets called for both tokens. Later parser does `pop` after `command_args` and as a result it pops a wrong value. 
Also I've added `empty?` method to the `StackState` class to use it in tests and rely on the interface.
Found it during stress testing (~40k files from rubygems)
> Fix parsing of `let (:a) { m do; end }`.

- lib/parser/ruby24.y
- lib/parser/ruby25.y
- lib/parser/ruby26.y
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/502
Fixes https://github.com/whitequark/parser/issues/501.
This commit tracks upstream commit ruby/ruby@f168dbd.
The spec says `SINCE_2_0` because 1.8 doesn't emit empty parens (so there's no `s(:begin)` in the ast) and 1.9 fails parsing it (no ideas why).
There's one test in the suite that verifies it - https://github.com/whitequark/parser/blob/master/test/test_parser.rb#L4128-L4164 - and it expect exactly what I described above. @whitequark do you remember why this syntax is not supported by 1.9?
> Fix cmdargs after command_args followed by tLBRACE_ARG.

- doc/AST_FORMAT.md
- lib/parser/builders/default.rb
- lib/parser/ruby26.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@7f95eed.
Closes https://github.com/whitequark/parser/issues/504
> ruby26.y: Endless ranges support.

- lib/parser/ast/processor.rb
An easy test case is to use `bin/ruby-parse -L`, which uses a `Processor` to recurse over the tree:
```
$ ruby-parse -L -e 'foo(**y)'
s(:send, nil, :foo,
s(:hash,
s(:kwsplat,
s(:send, nil, :y))))
foo(**y)
~~~ selector
~ end
~ begin
~~~~~~~~ expression
s(:hash,
s(:kwsplat,
s(:send, nil, :y)))
foo(**y)
~~~ expression
s(:kwsplat,
s(:send, nil, :y))
foo(**y)
~~ operator
~~~ expression
```
```
$ ruby-parse -L -e 'foo(**y)'
s(:send, nil, :foo,
s(:hash,
s(:kwsplat,
s(:send, nil, :y))))
foo(**y)
~~~ selector
~ end
~ begin
~~~~~~~~ expression
s(:hash,
s(:kwsplat,
s(:send, nil, :y)))
foo(**y)
~~~ expression
s(:kwsplat,
s(:send, nil, :y))
foo(**y)
~~ operator
~~~ expression
s(:send, nil, :y)
foo(**y)
~ selector
~ expression
```
Or, in diff form:
```diff
diff --git a/before b/after
index …
```
> AST::Processor: Recurse into `kwsplat`s

- lib/parser/lexer.rl
- test/test_parser.rb
That's a regression introduced in f0a5c6b5a55ccadc784489d966efc8975b3f4e32.
`fgoto` doesn't exit from `advance`, so `@command_state` remains the same and later `arg_or_cmdarg` can properly select the next state. Sorry, that was not obvious in https://github.com/whitequark/parser/pull/498.
@whitequark A quick question. `Parser#last_token` in some cases requires lexer to emit tokens one by one, but in this case we have to use `fgoto` to continue parsing without changing `@command_state`.  I feel like it can become a problem in the future. There are 54 occurrences of `fgoto` in the lexer, I know, some of them are safe because they do `fhold; fgoto ...`. But this specific action emits a token **and** does `fgoto`. Is there a way to rewrite `@command_state` somehow to not depend on …
> Fix parsing of 'm = -> *args do end'.

- lib/parser/ruby25.y
- test/test_parser.rb
See https://github.com/whitequark/parser/pull/431#issuecomment-392535487
> Revert parsing of '-> do rescue; end' for ruby25, it's valid only starting from 26.

- lib/parser/source/buffer.rb
- lib/parser/source/comment.rb
- lib/parser/source/comment/associator.rb
- lib/parser/source/map.rb
- lib/parser/source/range.rb
- lib/parser/source/tree_rewriter.rb
This PR does not impact the API.
The correct YARD annotations to express multiple types is as a list of multiple values ([source](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#Types_Specifier_List))
```
[Type1, Type2]
```
This PR corrects usages of `|` and `or` to achieve the same result.
---
The correct way to represent parameterized classes is using angled brackets ([source](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#Parametrized_Types))
```
Hash<String, Integer>
```
This PR corrects usage of parentheses to achieve the same result.
> Fix YARD type annotations

- lib/parser/lexer.rl
- test/test_parser.rb
The bug was introduced in https://github.com/whitequark/parser/commit/5ba072dba6d0f1270eab9cc782dad2fa5e759abe, but we didn't know about it. Sad, but our test suite doesn't cover all cases.
@whitequark I'm getting more and more unconfident in every patch that I send. Is there any way to improve our CI to handle trivial cases like this one? Any ideas?
Closes https://github.com/whitequark/parser/issues/518
> Partially revert 5ba072d and properly handle 'm = -> *args do end'.

- lib/parser/lexer.rl
- test/test_lexer.rb
Closes https://github.com/whitequark/parser/issues/522.
That's what MRI emits from the lexer:
```
$ ruby -y -e '1re' | grep token
-e:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input
Reading a token:
Next token is token tINTEGER (1.1-1.1: )
Shifting token tINTEGER (1.1-1.1: )
$1 = token tINTEGER (1.1-1.1: )
Reading a token:
Next token is token tIDENTIFIER (1.1-1.3: )
Next token is token tIDENTIFIER (1.1-1.3: )
Next token is token tIDENTIFIER (1.1-1.3: )
Next token is token tIDENTIFIER (1.1-1.3: )
Next token is token tIDENTIFIER (1.1-1.3: )
Next token is token tIDENTIFIER (1.1-1.3: )
Cleanup: discarding lookahead token tIDENTIFIER (1.1-1.3: )
```
And so the errors comes later from the parser.
> Fix parsing of ambiguous 1re.

- lib/parser/lexer.rl
- test/test_parser.rb
Closes #525 
I've checked other values that are handled by `operator_arithmetic` and `operator_rest`, none of them are affected by this issue.
> Fix parsing of 'm :key => m do; m() do end; end'.

- parser.gemspec
I noticed that following warnings occured while bundle installing.
```
$ bunlde install
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
```
SEE ALSO
https://blog.rubygems.org/2011/03/28/1.7.0-released.html
https://blog.rubygems.org/2009/05/04/1.3.3-released.html
> has_rdoc option was deprecated

- lib/parser/lexer.rl
- lib/parser/lexer/literal.rb
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/537
Introduced `Literal#supports_line_continuation_via_slash?` method that returns `true/false` depending on the type of the literal. I wasn't able to find any correlation between interpolation and escaping rules. Looks like that's a completely new separate property of the literal. Ruby ❤️ 
Added spec that verifies that `"\\\n"` gets properly escaped for all kinds of literals. @whitequark Please let me know if I should convert it from acceptance table to a list of plain assertions.
<details><summary>test data</summary>
<p>
``` ruby
$ cat test.rb
def `(str); str; end
p 'a\
b'
p <<'HERE'
a\
b
HERE
p %q{a\
b}
p "a\
b"
p <<"HERE"
a\
b
HERE
p %{a\
b}
p %Q{a\
b}
p %w{a\
b}
p %W{a\
b}
p %i{a\
b}
p %I{a\
b}
p :'a\
b'
p %s{a\
b}
p :"a\
b"
p /a\
b/ …
```
> Fix parsing of "\\\n" escaped sequences in various literals.

- lib/parser/lexer.rl
It is a meaningless condition. Because it checks the version is less than 2.4, but it has been checked the version is 1.8 or 1.9.
> Remove unreachable code from lexer.rl

- doc/AST_FORMAT.md
- lib/parser/builders/default.rb
- lib/parser/lexer.rl
- lib/parser/ruby27.y
- test/test_lexer.rb
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/541
This commit tracks upstream commit ruby/ruby@67c5747.
Special rule `'.:' w_space+` is required to reject code like `foo.: +`
> Add method reference operator.

- lib/parser/ruby27.y
This commit tracks upstream commit ruby/ruby@9cbb4dd.
Closes https://github.com/whitequark/parser/issues/542
> Refactored symbol rules.

- lib/parser/ruby27.y
This commit tracks upstream commit ruby/ruby@7006fde.
`xstring_contents` and `string_contents` rules are equivalent, so it doesn't change anything for parser.
> + ruby27.y: dsym should be treated as string.

- .travis.yml
- lib/parser/current.rb
Closes https://github.com/whitequark/parser/issues/561 and https://github.com/whitequark/parser/issues/562
> Bump ruby versions to 2.5.5 and 2.6.2.

- lib/parser/base.rb
- lib/parser/lexer.rl
Lexer needs to know current context (however `parser` is still responsible for controlling it).
@whitequark WDYT about using a shared context in `parser` and `lexer`? (parser can create it and assign to lexer via a simple setter, like we do with shared `diagnostics` and `static_env`). To make it available in the parser via `@context` (like it was before) and reduce commit size.
EDIT: applied it, please let me know if it should be reverted.
> Move Context to lexer.

- lib/parser/meta.rb
- test/helper.rb
I noticed that `:procarg0` was missing from `Meta::NODE_TYPES`.
I added a crude way to check that `Meta::NODE_TYPES` was complete and found 18 more were missing, although most seem to be for RubyMotion / Ruby 1.8...
> Add missing node types to Meta::NODE_TYPES

- .travis.yml
- lib/parser/current.rb
https://www.ruby-lang.org/en/news/2019/04/01/ruby-2-4-6-released/
> Bump 2.4 branch to 2.4.6.

- doc/AST_FORMAT.md
- lib/parser/builders/default.rb
- lib/parser/lexer.rl
- lib/parser/ruby27.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@95f7992.
Closes https://github.com/whitequark/parser/issues/568
> Add beginless ranges support.

- .travis.yml
- lib/parser/current.rb
- lib/parser/ruby26.y
Backport #560 to Ruby 2.6 branch.
This PR tracks upstream commit ruby/ruby@8bf06cb.
`xstring_contents` and `string_contents` rules are equivalent, so it doesn't change anything for parser.
Ruby 2.6.3 has been released.
https://www.ruby-lang.org/en/news/2019/04/17/ruby-2-6-3-released/
This seems to be the only syntax change from Ruby 2.6.2 to Ruby 2.6.3.
https://github.com/ruby/ruby/compare/v2_6_2...v2_6_3
> Bump 2.6 branch to 2.6.3

- lib/parser/lexer.rl
- lib/parser/messages.rb
- test/test_parser.rb
This commit tracks upstream commits ruby/ruby@330b376 and ruby/ruby@1432471.
Closes https://github.com/whitequark/parser/issues/573.
I've added one more rule to reject the code like
``` ruby
<<"HERE
```
Before this patch it'd throw `expected token tLSHIFT`
> Reject \n and \r in heredoc identifiers starting from 2.7.

- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@c05eaa9.
Closes https://github.com/whitequark/parser/issues/576
There's nothing to backport, the builder emits an error if the string has an invalid encoding (strings with mixed encodings are always invalid). But I've noticed that we have no specs for this case, I guess it's worth adding them.
> Add specs for heredocs with mixed encoding.

- lib/parser/lexer.rl
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@1cdaa17.
`else` branch does what previous versions of lexer would do.
@whitequark Should I split it into two machines (one for ivar, one for cvar, to avoid dynamic diagnostic name)? Or is it ok as it is?
Closes https://github.com/whitequark/parser/issues/578
> Reject numparams as symbol literals.

- lib/parser/lexer.rl
- test/test_lexer.rb
This commit tracks upstream commit ruby/ruby@c730c25.
Closes https://github.com/whitequark/parser/issues/579
meta and control chars are a bit broken, the algorithm of parsing escaped chars is recursive, and `\M-`/`\C-` prefixes work as functions:
```
"\C-<char>" => apply_C_mask_on(parse_escaped("<char>")
"\M-<char>" => apply_M_mask_on(parse_escaped("<char>")
```
however, in `lexer.rl` it's not recursive, and because of that it parse code like `"\C-\377"` incorrectly. I don't want to fix it for now, literally nobody uses syntax like this.
> Reject whitespaces in meta and control chars.

- lib/parser/messages.rb
- lib/parser/ruby27.y
- test/test_parser.rb
This commit tracks upstream commits ruby/ruby@140b811 and ruby/ruby@39ae88a.
Closes https://github.com/whitequark/parser/issues/583
> Reject safe navigator in LHS of mass-assignment.

- doc/AST_FORMAT.md
- lib/parser/ast/processor.rb
- lib/parser/builders/default.rb
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/527
@whitequark Do you see any better way to detect single argument / mlhs?
> Add custom visitor for procarg0 that supports both single argument and mlhs.

- lib/parser/runner/ruby_parse.rb
- test/test_runner_parse.rb
```
$ bin/ruby-parse --emit-json -e ''
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.3-compliant syntax, but you are running 2.6.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```
Closes https://github.com/whitequark/parser/issues/515
> Print empty string when --emit-json and empty input are given.

- lib/parser/lexer.rl
- lib/parser/ruby27.y
- test/test_parser.rb
This commit tracks upstream commits ruby/ruby@f169043, ruby/ruby@043f010, ruby/ruby@aa72118 and ruby/ruby@d365fd5
Closes https://github.com/whitequark/parser/issues/584
> 2.7 pipeline operator

- lib/parser/ruby27.y
This commit tracks upstream commit ruby/ruby@78a8888.
Closes https://github.com/whitequark/parser/issues/591
> ruby27.y: hoisted out f_rest_marg.

- .travis.yml
- lib/parser/current.rb
- lib/parser/ruby25.y
- https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-6-4-released/
- https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-5-6-released/
- https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-4-7-released/
Bump 2.6 branch from 2.6.2 to 2.6.3
https://github.com/ruby/ruby/compare/v2_6_3...v2_6_4
Bump 2.5 branch from 2.5.5 to 2.5.6
https://github.com/ruby/ruby/compare/v2_5_5...v2_5_6
There is the following change to the syntax:
```diff
-dsym	: tSYMBEG xstring_contents tSTRING_END
+dsym	: tSYMBEG string_contents tSTRING_END
```
This is a backport #560 to Ruby 2.5 branch.
cf. https://github.com/ruby/ruby/commit/764fe09
Bump 2.4 branch from 2.4.6 to 2.4.7
https://github.com/ruby/ruby/compare/v2_4_6...v2_4_7
There seems to …
> Bump maintenance branches to 2.6.3, 2.5.6, and 2.4.7

- parser.gemspec
This PR fixes the following build error when using Ruby 2.7.
```console
% cd path/to/parser
% ruby -v
ruby 2.7.0dev (2019-08-30T07:09:08Z master 998ee350b9) [x86_64-darwin17]
% bundle install
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 10.5.0
Using ast 2.4.0
Using bundler 1.17.3
Using cliver 0.3.2
Using json 2.2.0
Using net-http-persistent 1.4.1
Using minitest 5.11.3
Using kramdown 2.1.0
Using simplecov-html 0.10.2
Using yard 0.9.20
Using parser 2.6.3.0 from source at `.`
Using docile 1.1.5
Using gauntlet 2.1.0
Using simplecov 0.15.1
Fetching racc 1.4.14 (was 1.4.15)
Installing racc 1.4.14 (was 1.4.15) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native …
```
> Bump racc dependency to 1.4.15

- lib/parser/ruby27.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@53b3be5.
Closes #595.
> + ruby27.y: Fix parsing of mutiple assignment with rescue modifier

- lib/parser/lexer.rl
- test/test_parser.rb
Fixed #604 
The idea is simple: we have an instance variable `@command_start` (I renamed it to follow MRI naming) and a local variable `cmd_state`. Initially it's set to `true` (because we are in the beginning of the line, we do the same thing on `\n` and so does MRI), in the `advance` method we copy ivar to lvar to use this "snapshot" everywhere, `arg_or_cmdarg` now takes this lvar as an argument.
There's 1 small difference between MRI and parser: we change lvar in one place (on newlines) because we don't emit it and simply do `fgoto expr_value` while MRI emits it. So in this case we change "command mode" for the current token, and that's the only exception. Everywhere else we change "command mode" for next token by changing ivar.
I tested it with rubocop (CI will show it), opal and …
> fix parsing of 'm a + b do end'

- doc/AST_FORMAT.md
- lib/parser/builders/default.rb
- lib/parser/meta.rb
- lib/parser/ruby27.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@6a9ce1f.
Closes https://github.com/whitequark/parser/issues/603
> Add `kwnilarg` for `**nil` argument

- lib/parser/source/tree_rewriter.rb
Follow https://github.com/ruby/ruby/pull/2395.
RuboCop's CI of Ruby 2.7 matrix is failing. This is due to a deprecation warning in Ruby 2.7.
```console
1) RuboCop::CLI when BlockDelimiters has braces_for_chaining style
corrects SpaceBeforeBlockBraces, SpaceInsideBlockBraces offenses
Failure/Error: expect($stderr.string).to eq('')
expected: ""
got:
"/usr/local/bundle/gems/parser-2.6.4.0/lib/parser/source/tree_rewriter.rb:284:
warning: The last
argu...parser-2.6.4.0/lib/parser/source/tree_rewriter.rb:288:
warning: for `trigger_policy' defined here\n"
```
https://circleci.com/gh/rubocop-hq/rubocop/67195
This PR suppress the following Ruby 2.7's warning.
```console
% cd path/to/parser
% bundle exec rake
(snip)
/Users/koic/src/github.com/whitequark/parser/lib/parser/source/tree_rewriter.rb:284: …
```
> Follow "Separate Keyword Arguments from Positional Arguments"

- lib/parser/lexer.rl
- test/test_lexer.rb
- test/test_parser.rb
Part of https://github.com/whitequark/parser/pull/613
> emit tMETHREF as tDOT+tCOLON for rubies < 27.

- lib/parser/lexer.rl
- test/test_lexer.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@3a3f48f.
Closes https://github.com/whitequark/parser/issues/610
I've added a bunch comments, please LMK if there's anything that could be improved.
Also I've fixed parsing of `.:` operator for pre-27 lexer. Previously it was emitted as `tMETHREF` for all versions of lexer, but since it's a 27-specific token we had an "unknown token " error for pre-27 parsers.
> + lexer.rl: support comments before leading dot in 27 mode.

- lib/parser/source/tree_rewriter.rb
Follow up of https://github.com/whitequark/parser/issues/608#issuecomment-531774628.
RuboCop's CI of Ruby 2.7 matrix is failing. This is due to a deprecation warning in Ruby 2.7.
```console
/usr/local/bundle/gems/parser-2.6.4.1/lib/parser/source/tree_rewriter.rb:269:
warning: The last argument is used as the keyword parameter
/usr/local/bundle/gems/parser-2.6.4.1/lib/parser/source/tree_rewriter/action.rb:16:
warning: for `initialize' defined here
```
https://circleci.com/gh/rubocop-hq/rubocop/68131
cf. https://bugs.ruby-lang.org/issues/14183
> Suppress keyword argument warnings in Ruby 2.7

- lib/parser/lexer.rl
- test/test_lexer.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@2698f13.
`@10` (well, starting from https://github.com/whitequark/parser/issues/616 it's `_10`) gives a syntax error
Closes https://github.com/whitequark/parser/issues/615
> + lexer.rl: changed max numparam to `@9`

- .travis.yml
- lib/parser/current.rb
https://www.ruby-lang.org/en/news/2019/10/02/ruby-2-4-9-released/
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-5-7-released/
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/
> * Bump ruby versions to 2.4.9, 2.5.7 and 2.6.5.

- lib/parser.rb
- lib/parser/helpers/circular_argument_reference.rb
- lib/parser/messages.rb
- lib/parser/ruby27.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@0162e7e.
Closes https://github.com/whitequark/parser/issues/621
```
$ bin/ruby-parse --27 -e 'm { |a: proc { 1 + a }| }'
(fragment:0):1:6: error: circular argument reference a
(fragment:0):1: m { |a: proc { 1 + a }| }
(fragment:0):1:      ^             ~
```
> - ruby27.y: reject circular argument reference.

- doc/AST_FORMAT.md
- lib/parser/builders/default.rb
- lib/parser/meta.rb
- lib/parser/ruby27.y
- lib/parser/static_environment.rb
- test/test_parser.rb
This commit tracks upstream commits ruby/ruby@62d4382 and ruby/ruby@6279e45.
Closes #624 
Feel free to leave any comments, I'll merge it in a few days
> - ruby27.y: add "arguments forwarding"

- lib/parser/builders/default.rb
- lib/parser/context.rb
- lib/parser/max_numparam_stack.rb
- lib/parser/messages.rb
- lib/parser/ruby27.y
- test/test_parser.rb
This commit tracks upstream commits ruby/ruby@2fd4655 and ruby/ruby@82e840a.
Closes https://github.com/whitequark/parser/issues/626
> + ruby27.y: treat numparams as locals outside numblock.

- doc/AST_FORMAT.md
- lib/parser/builders/default.rb
- lib/parser/lexer.rl
- lib/parser/meta.rb
- lib/parser/ruby27.y
- test/test_lexer.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@fb6a489.
Closes https://github.com/whitequark/parser/issues/632
> + ruby27.y: reverted method reference operator (added in #634)

- lib/parser/lexer.rl
- lib/parser/ruby27.y
- test/test_lexer.rb
- test/test_parser.rb
This rule was the only one that didn't unset current_arg.
Thus, `def foo(var: bar { || var }) var end` is now a valid syntax.
This commit tracks upstream commits ruby/ruby@7c22898 and ruby/ruby@ed90ec3.
Closes https://github.com/whitequark/parser/issues/629 (that allows this syntax by fixing this rule)
Closes https://github.com/whitequark/parser/issues/630 (that removes the rule and changes lexer to emit a different sequence of terminals and use a different rule that allows new syntax).
It's easier to apply them both.
> + ruby27.y: removed opt_block_args_tail: tOROP rule.

- lib/parser/lexer.rl
- lib/parser/messages.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@a58b4ee.
We used `@paren_nest` only for parentheses, but MRI uses them also for brackets and curly braces. Previously it was ok, but now they use it to generate this warning.
Closes https://github.com/whitequark/parser/issues/631
> + lexer.rl: warn on `...` at EOL.

- README.md
- test/test_parser.rb
Added tests from ruby/ruby@ade0388.
Closes https://github.com/whitequark/parser/issues/627.
If anyone wants to implement it you are welcome. I'm pretty sure nobody cares about it.
> * README.md: documented compatibility issue with EOF chars after embedded documents

- lib/parser/lexer.rl
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@4d615a0.
Closes https://github.com/whitequark/parser/issues/638
Before 2.7 code like
``` ruby
"#@1"
```
was interpreted as interpolation of the `@1` instance variable. Starting from 2.7 it's just a plain string.
@whitequark Could you take a look please? Do you see any better solution? Initially I tried to stick to existing `interp_var` rule (by setting a flag in the local variable and checking it in the code that emits ivar). However, its handler (`extend_interp_var`) emits `#{` and I don't think that un-doing it (and doing `literal.extend_string` afterwards) is a reliable solution.
By the way, have you ever considered branching lexer?
> - lexer.rl: parse embedded ivars/cvars starting with digit as str

- lib/parser/lexer/dedenter.rb
- test/test_parser.rb
Closes #640 
I'm not sure what exactly caused this bug, but `Dedenter` removed non-whitespace character because of wrong values in `space_begin`/`space_end`.
Instead of debugging it I decided to rewrite it into a less efficient, but way more readable implementation.
I manually checked all test cases in `test_dedenting_heredoc` and found one more bug related to tabs (that is fixed now).
> - dedenter.rb: fixed over-dedenting of squiggly heredocs

- doc/AST_FORMAT.md
- lib/parser.rb
- lib/parser/ast/processor.rb
- lib/parser/base.rb
- lib/parser/builders/default.rb
- lib/parser/lexer.rl
- lib/parser/messages.rb
- lib/parser/meta.rb
- lib/parser/ruby27.y
- lib/parser/variables_stack.rb
- test/helper.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@9738f96.
Closes https://github.com/whitequark/parser/issues/571
No rush, this commit is 100% isolated (literally 0 deletions)
Specs cover 100% of the new grammar.
Feel free to to add comments!
A bunch of code for error handling is still missing, but at least that's something to discuss.
> 2.7 Pattern matching

- lib/parser/lexer/dedenter.rb
This PR prevents the following error when processing binary encoded code.
```ruby
"\xC0".split # => ArgumentError (invalid byte sequence in UTF-8)
```
RuboCop's CI has detected this error.
https://circleci.com/gh/rubocop-hq/rubocop/78846
> - dedenter.rb: prevent `ArgumentError` when processing binary encoded code

- parser.gemspec
Add [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file. This'll allow people to more easily access the source code, raise issues and read the changelog. These `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, and `source_code_uri` links will appear on the rubygems page at https://rubygems.org/gems/parser after the next release.
> Add project metadata to the gemspec

- doc/AST_FORMAT.md
- lib/parser/ast/processor.rb
- lib/parser/builders/default.rb
- lib/parser/messages.rb
- lib/parser/meta.rb
- lib/parser/ruby27.y
- test/test_parser.rb
This PR aims to fix a few incompatibilities with MRI (based on the recently published [ruby/spec](https://github.com/ruby/spec/blob/master/language/pattern_matching_spec.rb) tests for pattern matching).
```ruby
case {a: 1}
in {"#{x}": 1}
end
```
For `case ... in` the empty else clause has a different meaning than no else clause (the first one returns `nil`, the second raises NoMatchingPattern); thus, we need to make them distinguishable in the resulting AST.
> Improve pattern matching compatibility

- lib/parser/lexer.rl
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/653
`\s*` was missing and so
```ruby
m
#
.n
```
was valid, but not
```ruby
m
#
.n
```
> - lexer.rl: allow spaces before comments-before-leading-dot.

- README.md
- Fix documentation of modern AST format to include
emit_arg_inside_procarg0. This allows users to mirror what
`Parser::Builders::Default.modernize` does.
> Fix modern documentation to mention emit_arg_inside_procarg0

- doc/AST_FORMAT.md
- lib/parser/builders/default.rb
- lib/parser/ruby27.y
- test/test_parser.rb
This change takes trailing comman into account for `array_pattern_with_tail` expression location:
```
in foo,
~~~ expression
in foo,
~~~~ expression
```
Currently, we lose comma location information, which makes it hard for rewriters to deal with this case.
> + ruby27.y: fix array pattern with tail source map

- lib/parser/ruby27.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@93aaa0b.
This is the following commit cherry picked from 2.8.0-dev to 2.7.1.
https://github.com/ruby/ruby/commit/d25a4f4
Closes #655.
> + ruby27.y: Allow trailing comma in hash pattern

- lib/parser/ruby27.y
- test/test_parser.rb
This commit tracks upstream commits ruby/ruby@f5c904c and ruby/ruby@c8d0bf0
that have been cherry-picked in 2.7.1 (ruby/ruby@004c298 and ruby/ruby@44f7e38)
Closes https://github.com/whitequark/parser/issues/656
> + ruby27.y: allow newlines inside braced pattern.

- .travis.yml
- lib/parser/current.rb
Not sure if travis support them.
Also removed all versions that are not longer maintained from the travis matrix.
Closes https://github.com/whitequark/parser/issues/663
> * Bump ruby versions to 2.4.10, 2.5.8, 2.6.6, 2.7.1.

- .travis.yml
Follow https://github.com/whitequark/parser/pull/665/commits/3274464.
Currently, Ruby 2.4.10 is available on Travis CI.
https://travis-ci.community/t/cannot-find-ruby-2-4-10-and-2-6-6-using-rvm-ubuntu-16-04-xenial/7962
> CI against Ruby 2.4.10

- lib/parser/source/tree_rewriter.rb
- lib/parser/source/tree_rewriter/action.rb
- test/test_source_tree_rewriter.rb
This PR adds methods for merging `Source::TreeRewriter`s.
There is also a simple method to check if a `Source::TreeRewriter` is `empty?`, i.e. if it has received any non-trivial command.
I wanted to use these methods to improve the [autocorrection's API of rubocop](https://github.com/rubocop-hq/rubocop/pull/7868), which could benefit from building a `TreeRewriter`, check if any correction was actually made, and combine them later in the process.
> + Source::TreeRewriter: Add #merge, #merge! and #empty?

- lib/parser/source/range.rb
- test/test_source_range.rb
> + Add Source::Range#eql? and hash

- doc/AST_FORMAT.md
The commit corrects an example in [AST format document](https://github.com/whitequark/parser/blob/master/doc/AST_FORMAT.md) in the "Multiple Assignment" section.
> rectify multiple assignment example

- lib/parser/builders/default.rb
- test/test_parser.rb
> - ruby27.y: reject invalid lvar in pattern matching

- doc/AST_FORMAT.md
- lib/parser.rb
- lib/parser/ast/processor.rb
- lib/parser/builders/default.rb
- lib/parser/meta.rb
- lib/parser/ruby28.y
- lib/parser/source/map/endless_definition.rb
- test/test_lexer.rb
- test/test_parser.rb
> + ruby28.y: endless method definition

- lib/parser/source/tree_rewriter.rb
- lib/parser/source/tree_rewriter/action.rb
- test/test_source_tree_rewriter.rb
This PR contains two independent optimizations for the `Source::TreeRewriter`.
The first one changes building the tree from `O(n^2)` to `O(n log(n))` where `n` is the number of rewriting actions.
The second one is of lesser importance and changes applying the tree from `O(n * s)` to `O(n + s)`, where `s` is the length of the source.
While I doubt users of `RuboCop` will notice the speedup but this will make a big difference for the conversion and annotation of source files into HTML by `DeepCover` which was ridiculously slow for long source files.
> Rewriter optimizations

- doc/AST_FORMAT.md
- lib/parser/ast/processor.rb
- lib/parser/builders/default.rb
- lib/parser/meta.rb
- lib/parser/ruby28.y
- test/test_parser.rb
> + ruby28.y: add right hand assignment

- .travis.yml
- Rakefile
- lib/parser/diagnostic.rb
- lib/parser/lexer.rl
- lib/parser/messages.rb
- lib/parser/source/tree_rewriter.rb
- parser.gemspec
- test/helper.rb
- test/parse_helper.rb
- test/test_diagnostic.rb
- test/test_diagnostic_engine.rb
- test/test_lexer.rb
- test/test_parser.rb
- test/test_runner_parse.rb
- test/test_runner_rewrite.rb
- test/test_source_buffer.rb
- test/test_source_comment_associator.rb
- test/test_source_range.rb
- test/test_source_rewriter.rb
- test/test_source_tree_rewriter.rb
1. added `if false; testEof; end` at the bottom of `Lexer#advance` to prevent warnings about unused variable `testEof`. It has 0 runtime cost.
2. fixed formatting in a few places
3. changed test task definition to run tests in verbose mode (like `ruby -w` would do)
4. For some reason `"" % {}` gives a warning (same with `Kernel#sprintf`, no idea why). Added a utility method to perform interpolation on messages only if there's something to interpolate.
5. added parentheses to all `m /regex/` calls
6. added `_` prefix to unused variables.
I'm getting 0 warnings locally when running `rake test`/`rake test_cov`
Closes https://github.com/whitequark/parser/issues/684
> * fixed all warnings. tests are running in verbose mode now.

- README.md
- lib/parser/diagnostic/engine.rb
- lib/parser/runner/ruby_rewrite.rb
- lib/parser/source/buffer.rb
- lib/parser/tree_rewriter.rb
- test/parse_helper.rb
- test/test_diagnostic.rb
- test/test_lexer.rb
- test/test_parser.rb
- test/test_source_buffer.rb
- test/test_source_comment.rb
- test/test_source_map.rb
- test/test_source_range.rb
- test/test_source_rewriter.rb
- test/test_source_rewriter_action.rb
- test/test_source_tree_rewriter.rb
I find it inconvenient that a `Source::Buffer` can not be created in one go. I feel that creation of mostly immutable objects should be, if possible, atomic.
Could we add a `source:` named parameter to the constructor of `Buffer`?
> Allow creating of Buffer with source

- lib/parser/source/comment/associator.rb
- test/helper.rb
- test/test_meta.rb
- test/test_source_comment_associator.rb
and also any node with children in inverted order.
See test file for example.
An faster alternative solution would be to instead figure out which nodes might have such a situation and visit them accordingly (are there any other than postfix `if/unless/while`?), but this slower solution seemed the most robust.
> - fix Comment.associate for postfix conditions/loops

- lib/parser/ruby28.y
This commit tracks upstream commit ruby/ruby@276859e.
Closes https://github.com/whitequark/parser/issues/657
> + ruby28.y: unify kwrest and no-kwrest rules.

- lib/parser/ruby28.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@d7d0d01.
Closes https://github.com/whitequark/parser/issues/687
> + ruby28.y: support rescue modifier in endless method definition.

- lib/parser/source/range.rb
- test/test_source_range.rb
Closes https://github.com/whitequark/parser/issues/692
> + Added Parser::Source::Range#to_range.

- test/test_ast_processor.rb
- test/test_base.rb
this way we have to either
1. register an `on_*` handler in the AST::Processor
2. or explicitly add a node name to the `LEAF_NODES` list
> make sure that all nodes are known for AST::Processor.

- lib/parser/runner.rb
- test/test_runner_parse.rb
This PR adds switches to `ruby-parse` and `ruby-rewrite` to turn off `emit_lambda`, etc.
I thought that `--legacy` would be an easy to remember switch and also added `--legacy-lambda`, etc. just because.
Usecase: The actual AST printed / passed on to rewriter is quite important, so these switches should be available. In particular, `rubocop` [currently does not turn them on](https://github.com/rubocop-hq/rubocop-ast/issues/10), so writing/debugging cops using `ruby-parse` is much more error prone.
New help look like:
```
$ ruby-parse -h
Usage: ruby-parse [options] FILE|DIRECTORY...
--18                         Parse as Ruby 1.8.7 would
--19                         Parse as Ruby 1.9.3 would
--20                         Parse as Ruby 2.0 would
--21                         Parse as Ruby 2.1 …
```
> + ruby-[parse, rewrite]: add legacy switches

- lib/parser/source/range.rb
- lib/parser/source/tree_rewriter.rb
- lib/parser/source/tree_rewriter/action.rb
- test/test_source_tree_rewriter.rb
This PR provides `TreeRewriter` with:
* improved merging (allowing different ProcessedSource or offsetting)
* two representations of the rewriter (a basic one and a complete one)
*Background*:
I was looking at [erb-lint](https://github.com/Shopify/erb-lint) and they do some processing on some excerpts of erb files. Later, they want to combine the rewriting actions on the original erb (with an offset).
With the upcoming RuboCop 1.0 this would be tricky, and this made me realize that the two avenues I was thinking about were not available (transferring a `TreeRewriter` with an offset, or at least having a representation of the TreeRewriter so we could recreate the actions on a different source and with an offset). This PR allows both avenues.
I added a minor doc change too. Let me know if I …
> + Source::TreeRewriter: Improved merging and representations

- lib/parser/context.rb
- lib/parser/macruby.y
- lib/parser/ruby18.y
- lib/parser/ruby19.y
- lib/parser/ruby20.y
- lib/parser/ruby21.y
- lib/parser/ruby22.y
- lib/parser/ruby23.y
- lib/parser/ruby24.y
- lib/parser/ruby25.y
- lib/parser/ruby26.y
- lib/parser/ruby27.y
- lib/parser/ruby28.y
- lib/parser/rubymotion.y
- parser.gemspec
- test/helper.rb
- test/parse_helper.rb
- test/test_parser.rb
Previously we didn't push context for module and lambda arguments and so we didn't reject some code (or we rejected what's allowed).
However, examples that should've raised errors are complicated and it's very unlikely that any code was affected. At least no related issues were reported.
Examples of code that is accepted/rejected differently after this change:
1. `->(a) { module M; _1; end }`
We didn't push context for module M, and so argument `a` conflicted with implicit parameter `_1`. In Ruby module opens a new scope and so `_1` is just a regular local variable.
2. `class A; ->(a = (return; 1)) {}; end`
This code is valid, because `return` is a part of the lambda. But we didn't store this fact internally, and so it was rejected before.
Both examples described above (and all similar …
> - ruby*.y: fixed context inside lambda args and module.

- README.md
- doc/AST_FORMAT.md
- lib/parser/ast/processor.rb
- lib/parser/builders/default.rb
- lib/parser/meta.rb
- lib/parser/ruby27.y
- lib/parser/ruby28.y
- lib/parser/runner.rb
- test/test_parser.rb
The reason is that Ruby 2.8 supports the following code:
`def m(a, b, ...); end`
If set to false (the default):
1. `def m(...) end` is emitted as
```
s(:def, :m, s(:forward_args), nil)
```
2. `def m(a, b, ...) end` is emitted as
```
s(:def, :m,
s(:args, s(:arg, :a), s(:arg, :b), s(:forward_arg)))
```
If set to true it uses a single format:
1. `def m(...) end` is emitted as
```
s(:def, :m, s(:args, s(:forward_arg)))
```
2. `def m(a, b, ...) end` is emitted as
```
s(:def, :m, s(:args, s(:arg, :a), s(:arg, :b), s(:forward_arg)))
```
This is necessary to backport https://github.com/ruby/ruby/commit/f8b4340fa2c254cd093ebc3bc70d2d0c46ea9997
I'll keep it open for a few days, feel free to leave comments/suggestions.
> + Added `emit_forward_arg` compatibility flag.

- lib/parser/builders/default.rb
- lib/parser/ruby28.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@f8b4340.
Closes https://github.com/whitequark/parser/issues/702
> + ruby28.y: accept leading args before forward arg.

- lib/parser/lexer.rl
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@c0ba35f.
Closes https://github.com/whitequark/parser/issues/704
> + lexer.rl: reject `->...` and `->(...)` with the same error.

- doc/AST_FORMAT.md
- lib/parser/ast/processor.rb
- lib/parser/builders/default.rb
- lib/parser/meta.rb
- lib/parser/ruby28.y
- test/test_parser.rb
This commit tracks upstream commits ruby/ruby@ddded11 and ruby/ruby@f7906a7.
Closes https://github.com/whitequark/parser/issues/711
> + ruby28.y: add find pattern.

- lib/parser/macruby.y
- lib/parser/ruby18.y
- lib/parser/ruby19.y
- lib/parser/ruby20.y
- lib/parser/ruby21.y
- lib/parser/ruby22.y
- lib/parser/ruby23.y
- lib/parser/ruby24.y
- lib/parser/ruby25.y
- lib/parser/ruby26.y
- lib/parser/ruby27.y
- lib/parser/ruby28.y
- lib/parser/rubymotion.y
- test/parse_helper.rb
- test/test_parse_helper.rb
- test/test_parser.rb
```sh
$ ruby-parse -L -e "alias foo x"
s(:alias,
s(:sym, :foo),
s(:sym, :x))
alias foo x
~~~~~ keyword         
~~~~~~~~~~~ expression
s(:sym, :foo)
alias foo x
~ begin       # <<< error
~~~ expression
s(:sym, :x)
alias foo x
~ begin     # <<< error
~ expression
```
I couldn't find a (simple) way to add a test, but it looks like tests aren't necessarily precise to that level. For example I temporarily changed `%i[foo]` to erroneously generate a `begin` and no test fail. Since this hasn't been noticed in so many years, clearly it's not super important. I noticed it by pure chance.
Let me know if it's necessary to add a test (which would probably involve changing `assert_parses` to accept some kind of annotation like `! begin` or accept a block to run extra checks...
> - Fix locations for alias / undef nodes with internal symbols

- lib/parser/ruby27.y
- lib/parser/ruby28.y
- test/test_parser.rb
Resolves: https://github.com/rubocop-hq/rubocop/issues/8165
This PR fixes the following error for pattern matching.
```console
% ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin17]
% ruby-parse -e 'pattern in { Foo: foo }'
(fragment:0):1:14: error: formal argument cannot be a constant
(fragment:0):1: pattern in { Foo: foo }
(fragment:0):1:              ^~~~
```
Because of that, this PR removes the check for kwarg name to a hash object, and accepts the same case as Ruby:
```console
% ruby -ce 'pattern in { Foo: foo }'
-e:1: warning: Pattern matching is experimental, and the behavior may
change in future versions of Ruby!
Syntax OK
```
It makes the same changes for ruby28.y (experimental).
> - ruby27.y: accept const names as hash keys for pattern matching

- doc/AST_FORMAT.md
- lib/parser/ast/processor.rb
- lib/parser/builders/default.rb
- lib/parser/meta.rb
- test/test_parser.rb
(according to https://github.com/whitequark/parser/pull/676#issuecomment-650327931)
2.8.0-dev is not released, so I think we are free to change it.
> + emit "endless method def" as `:def` node.

- lib/parser.rb
- lib/parser/builders/default.rb
- lib/parser/source/map/method_definition.rb
- test/test_parser.rb
This way one can ask `loc.end` or `loc.assignment` of all method definitions
> - unify locations for normal and endless method definition

- lib/parser/base.rb
- test/test_parser.rb
In some circumstances (when reaching the EOF too early), [`racc` erroneously returns `false` instead of `nil`](https://github.com/ruby/racc/pull/136).
Even though it's an upstream issue, the fix is so simple that I thought it was worthwhile to circumvent it.
This PR also improves the documentation for non-fatal cases. There are no other tests with `all_errors_are_fatal` set to `false`.
> - Parser#parse returns nil instead of false if error is thrown

- lib/parser/builders/default.rb
- lib/parser/max_numparam_stack.rb
- lib/parser/messages.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@d47e124.
Closes https://github.com/whitequark/parser/issues/723.
> + ruby28.y: reject assignment to numparam.

- .github/workflows/test.yml
See discussion in https://github.com/whitequark/parser/pull/731
> Configure GitHub Actions

- lib/parser/messages.rb
- lib/parser/ruby30.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@53ba9fb.
Closes #730
What's interesting, the following syntax is still allowed:
```ruby
def foo=() = 42 rescue nil
def self.foo=() = 42
def self.foo=() = 42 rescue nil
```
> + ruby30.y: reject endless setter.

- lib/parser/meta.rb
Last use was replaced by zsuper in cbbb6bbd28cac20dc1a618c7d4779dce12f5f749.
meta also mentions 'ident'.  I think it is used only temporarily by the parser and never shows in final ASTs.  Is that right?
> meta: root is no longer used

- lib/parser/source/range.rb
This avoids the creation of 4 temporary objects
> + Optimize Range#column_range

- parser.gemspec
If .gitignore is a part of the .gem it's impossible to include source of
the locally installed parser (using bundle install --path ./vendor) because git
automatically excludes all gitignore-d files (including all parsers and lexer).
> Exclude .gitignore from the package to support vendoring.

- .gitignore
- parser.gemspec
Hi @iliabylich,
As discussed in #743, here's the PR, dropping `git` in gemspec.
Rationale at: https://docs.rubocop.org/rubocop-packaging/cops_packaging.html#gemspec-git-rationale
This helps in maintaining this in Debian and other downstream 💫 
Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>
> Drop `git` in gemspec

- test/parse_helper.rb
raising an error in the `else` branch makes 42 tests to fail (i.e. there are 42 breaking MRI changes that we are aware of)
@mbj PTAL, do you have anything to add?
> test older parsers don't throw non-syntax errors on new syntax

- lib/parser/meta.rb
I presume this dates from before Ruby 2.0 as minimum target.
> Simplify code

- .travis.yml
- lib/parser/current.rb
Ruby 2.7.2 has been released.
https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/
It seems like no changes have been made to ruby27.y where Parser gem should be changed (backported).
https://github.com/ruby/ruby/compare/v2_7_1...v2_7_2
> * Bump 2.7 branch to 2.7.2

- parser.gemspec
It was removed while dropping git in gemspec (a70ed2ade8f6d4c12d0d30069a3bde0d447fb7b9).
> Add LICENSE.txt to the gem

- lib/parser/source/buffer.rb
- test/test_source_buffer.rb
`#line_begins`:
- store `line_begin` instead of `[line_begin, index]`
- simplify code by storing an additional "virtual" line_begin at the end
caches for `position` => line / column: Use same cache instead of two.
`#decompose_position`: use cache there too
I added tests for behavior of some methods with out-of-range arguments.
Behavior arguably less bad after this PR.
> * Optimize `SourceBuffer` line and column handling

- lib/parser/source/buffer.rb
- test/test_source_buffer.rb
Builds on #755 and makes `SourceBuffer` freezable. Currently attempting to freeze before caches are build will crash.
> Source buffer freeze

- lib/parser/ruby30.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@4ed0c33.
Closes #751
> + ruby30.y: reject setters in all endless method defs.

- lib/parser/builders/default.rb
- lib/parser/ruby30.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@52c630d.
Closes https://github.com/whitequark/parser/issues/753
@palkan Could you confirm that you don't use `Builder#rassign`/`multi_rassign` please? This API is a part of the 3.0 parser, so I guess only you can use it 😄
> + ruby30.y: use `=>` for one-line pattern matching.

- lib/parser/source/buffer.rb
- test/test_base.rb
- test/test_source_buffer.rb
Build on #756 so that `SourceBuffer` is `Ractor`-shareable.
Since `Node`, `Range` and `Map` are typically frozen, there's probably no issue with them.
`SourceBuffer` is the only non-frozen element in the chain.
`Ractor` is still evolving, maybe you'll want to wait until X-mas to merge this...
> Make `SourceBuffer` Ractor-shareable. Basic test for `Node`.

- lib/parser/lexer.rl
- test/test_parser.rb
It fixes parsing of
```ruby
1 => foo
bar
```
```ruby
1 => A(foo)
```
and basically all single line patterns that consist of multiple tokens.
The second token of expr` in `pattern => expr` was interpreted in EXPR_BEG state instead of EXPR_ARG.
Closes #763
> - lexer.rl: don't perform lookahead after tASSOC.

- lib/parser/ruby30.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@bdd1d17.
Closes https://github.com/whitequark/parser/issues/754
I noticed that we have an exception to our rule that "all nodes have expression_l" - that's not true from the very beginning:
```sh
$ bin/ruby-parse --30 -L -e 'def m; end'
s(:def, :m,
s(:args), nil)
def m; end
~~~ keyword
~ name
~~~ end
~~~~~~~~~~ expression
s(:args)
```
^ `args` node has absolutely no source maps. `def foo = 42` also emits a dummy `args` node.
@marcandre @mbj @palkan Side question for this PR (I'm going to merge it anyway as it doesn't break anything), but what's your hunch on how many things are going to break if we make `s(:args)` nullable?
> + ruby30.y: allow endless method without arglist.

- lib/parser/lexer.rl
- lib/parser/messages.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@f5bb911.
Closes https://github.com/whitequark/parser/issues/762
> + lexer.rl: use more specific warning for ambiguous slash.

- README.md
- doc/AST_FORMAT.md
- lib/parser/ast/processor.rb
- lib/parser/builders/default.rb
- lib/parser/meta.rb
- lib/parser/ruby18.y
- lib/parser/runner.rb
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/761.
> + builder: emit implicit hash passed to a method call as kwargs

- lib/parser/builders/default.rb
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/772
So now
```
$ /bin/cat test.rb
<<~HEREDOC
#{}
#{}
HEREDOC
"#{}
#{}
"
"" ""
```
is parsed as
```
$ bin/ruby-parse --30 test.rb
(begin
(dstr
(begin)
(str "\n")
(begin)
(str "\n"))
(dstr
(begin)
(str "\n")
(begin)
(str "\n"))
(dstr
(str "")
(str "")))
```
(two first cases are equivalent, the third case is not affected, we still emit all empty strings)
> * do not emit truncated parts of squiggly heredoc

- lib/parser/builders/default.rb
Trivial fix: fix a spelling mistake in a comment. 'numbererd' -> 'numbered'.
> 'numbererd' -> 'numbered'

- README.md
- doc/AST_FORMAT.md
- lib/parser/ast/processor.rb
- lib/parser/builders/default.rb
- lib/parser/meta.rb
- lib/parser/ruby27.y
- lib/parser/ruby30.y
- lib/parser/runner.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@88f3ce1.
Closes https://github.com/whitequark/parser/issues/775
So, if compatibility flag is disabled:
+ 2.7 emits `foo in bar` as `in_match`
+ 3.0.. emits `foo in bar` as `match_pattern_p`, `foo => bar` as `match_pattern`
If enabled:
+ 2.7 emits `foo in bar` as `match_pattern` (because it throws)
+ 3.0.. emits `foo in bar` as `match_pattern_p`, `foo => bar` as `match_pattern`
This flag doesn't affect 3.0 at all. I think it's incorrect to emit `foo in bar` as `in_match` on 3.0. On 2.7 this node has a different meaning (throw vs true/false), and so it must be a different node.
It's a bit chaotic with the flag being disabled, but
1. There's no way to misinterpret throwing and bool versions (even when multiple grammars are used).
2. It doesn't …
> + ruby30.y: reintroduce `expr in pat`

- lib/parser/current.rb
ruby 3.0.0 is released and no need to check for dev version
> ruby-3.0 is released

- lib/parser/source/tree_rewriter.rb
- test/test_source_tree_rewriter.rb
This provide a short `inspect` for TreeRewriter. I thought it might be useful to add a summarized summary of the actions of the rewriter, either "empty", or a mix of additions (`+"insert me"@42`), deletions (`-55...60`) and replacements (`^"replacement"@77...88), but I can change of remove if that's too cryptic. The main goal was to avoid an `inspect` that was really very long.
> + `Source::TreeRewriter#inspect` [#728]

- .github/workflows/test.yml
- lib/parser/current.rb
- lib/parser/ruby27.y
- test/test_parser.rb
- https://www.ruby-lang.org/ja/news/2021/04/05/ruby-3-0-1-released/
- https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-7-3-released/
- https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-6-7-released/
- https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-5-9-released/
Bump 3.0 branch from 3.0.0 to 3.0.1
https://github.com/ruby/ruby/compare/v3_0_0...v3_0_1
Bump 2.7 branch from 2.7.2 to 2.7.3
https://github.com/ruby/ruby/compare/v2_7_2...v2_7_3
There is the leading arguments support to arguments forwarding change to the syntax.
Thas PR is backport #712 to Ruby 2.7 branch.
cf. https://github.com/ruby/ruby/commit/27fca66207f2c35f2f44f6a7cbbe6fd153546082
Bump 2.6 branch from 2.6.6 to 2.6.7 …
> * Bump maintenance branches to 3.0.1, 2.7.3, 2.6.7, and 2.5.9

- lib/parser/ruby30.y
- lib/parser/ruby31.y
- test/test_parser.rb
Fixes: #795.
This PR fixes false positives that comparison methods recognizes as a setter method.
> - fix a false positive for endless method definition

- lib/parser/builders/default.rb
I just happened to notice this via visual inspection (this regular expression happens to be problematic for Opal, see https://github.com/opal/opal/issues/2195 for workaround)
> vertical bar is not a valid character in an lvar name

- doc/AST_FORMAT.md
- lib/parser/ruby31.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@2186347.
Closes https://github.com/whitequark/parser/issues/790
> + ruby31.y: pin operator with expression

- lib/parser/source/comment.rb
- lib/parser/source/comment/associator.rb
- test/test_source_comment_associator.rb
In #184, it was noticed that `associate`'s result is unusable for separate nodes that might have identical content.
The method `associate_by_locations`, which uses locations instead of nodes as indices, was added as a workaround.
It was discussed at the time to change the definition of equality for `Node` (which was rejected) but it doesn't look like using `Hash#compare_by_identity` was discussed which surprises me. For any user of `parser` that does not play around its `Node`s and only uses those returned from parsing, this seems like the perfect solution.
This PR proposes to add `associate_by_identity` that does just that.
This would be helpful for rubocop/rubocop#9756 
If this is accepted, a release would be appreciated.
> + Add `associate_by_identity` as an alternate to `associate`

- lib/parser/ruby31.y
- test/test_parser.rb
Fixes https://github.com/whitequark/parser/issues/799.
> + ruby31.y: allow "command" syntax in endless method definition

- lib/parser/lexer.rl
- test/test_lexer.rb
This commit tracks upstream commit ruby/ruby@110f242.
Partially fixes https://github.com/whitequark/parser/issues/800
> + lexer.rl: reject `\u` after control/meta escape chars.

- .github/workflows/test.yml
- lib/parser/current.rb
- https://www.ruby-lang.org/en/news/2021/07/07/ruby-3-0-2-released/
- https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-7-4-released/
- https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-6-8-released/
Bump 3.0 branch from 3.0.1 to 3.0.2
https://github.com/ruby/ruby/compare/v3_0_1...v3_0_2
https://github.com/ruby/ruby/commit/110f242ef9b495037f59e4972ee102a8b8b372d5 listed in https://github.com/whitequark/parser/issues/800#issuecomment-840393324 is backported, but the issue has not yet been resolved at ruby31.y of Parser gem.
Bump 2.7 branch from 2.7.3 to 2.7.4
https://github.com/ruby/ruby/compare/v2_7_3...v2_7_4
Bump 2.6 branch from 2.6.7 to 2.6.8
https://github.com/ruby/ruby/compare/v2_6_7...v2_6_8
There seems …
> * Bump maintenance branches to 3.0.2, 2.7.4, and 2.6.8

- lib/parser/lexer.rl
- test/test_lexer.rb
CRuby only accepts ASCII characters except `[A-Za-z0-9]` as a delimiter
of percent literal, but the lexer accepts different characters.
For exmaple:
* CRuby accepts `%w^Dfoo^D`, but parser didn't (note: `^D` means 0x04)
* CRuby reject `%w1foo1`, but parser accepts
* CRuby reject `%w★foo★`, but parser accepts
This patch fixes the problems.
CRuby parses percent literals here: https://github.com/ruby/ruby/blob/6072239121360293dbd2ed607f16b6a11668999a/parse.y#L8718-L8815
I confirmed Ruby 1.8 or greater accept all ASCII characters except alnum as delimiters with the following code.
`test.rb`
```ruby
(0..127).each do |n|
next if /[a-zA-Z0-9()<>{}\[\]]/ =~ n.chr
eval "%q#{n.chr}foo#{n.chr}"
end
```
```
$ docker run -it --rm -v $(pwd)/test.rb:/tmp/test.rb rubylang/all-ruby env ALL_RUBY_SINCE=1.8 …
```
> - lexer.rl: fix incompatible delimiters on percent literal

- lib/parser/ruby31.y
- test/test_parser.rb
Closes #812.
This commit tracks upstream commit https://github.com/ruby/ruby/commit/fa87f72.
> + ruby31.y: Add pattern matching pin support for instance/class/global variables

- lib/parser/ruby31.y
- test/test_parser.rb
Closes #815.
This commit tracks upstream commit https://github.com/ruby/ruby/commit/ecb6d6a
> + ruby31.y: Allow omission of parentheses in one line pattern matching

- lib/parser/ruby31.y
- test/test_parser.rb
Closes #817.
This commit tracks upstream commit https://github.com/ruby/ruby/commit/c60dbcd
> + ruby31.y: Allow value omission in Hash literals

- lib/parser/lexer/dedenter.rb
- test/test_parser.rb
Firstly, this fixes an issue with non-interpolating squiggly heredocs, where line continuation characters should be ignored. Two things were broken:
- The line continuation backslash would be removed, as well as the subsequent carriage return
- The subsequent line would not be dedented.
For example, the following source:
```ruby
<<~'END'
foo \
bar
END
```
Would be parsed as follows:
```
(dstr
(str "foo ")
(str "  bar\n"))
```
With the change, the result is:
```
(dstr
(str "foo \\\n")
(str "bar\n"))
```
This also fixes an issue with interpolating squiggly heredocs, where an escaped backslash followed by a newline would be interpreted as a line continuation. This is issue #789.
In that case, the following source:
```ruby
<<~END
foo \\
bar
END
```
Would (again) be parsed as follows:
``` …
```
> - dedenter.rb: Fix squiggly heredoc line continuation handling

- test/test_parser.rb
Add more tests based on https://github.com/ruby/ruby/commit/297f9b8d4c4502aa2ba0eccf93dfce215a7b6dfe
> add tests for keyword argument value omission

- lib/parser/lexer.rl
- test/test_lexer.rb
- test/test_parser.rb
This fixes an issue where beginless ranges at the start of a line would be interpreted as continuing an expression starting on the previous line. Unlike leading dots for method calls, `..` and `...` at the start of a line do not continue an expression from the previous line.
Fixes #814.
> - lexer.rl: Fix handling of beginless ranges at start of line

- doc/AST_FORMAT.md
- lib/parser/builders/default.rb
- lib/parser/messages.rb
- lib/parser/ruby27.y
- lib/parser/ruby30.y
- lib/parser/ruby31.y
- test/test_parser.rb
There's a new rule in 3.1 that allows hash value to be omitted if it's equal to key:
```sh
$ ./miniruby -ve 'p({ rand: })'
ruby 3.1.0dev (2021-09-24T13:56:38Z master 40a65030e5) [x86_64-darwin20]
{:rand=>0.6152290626750991}
```
We backported it in https://github.com/whitequark/parser/pull/818, but there's one case that we missed - local variables can also be used:
```sh
./miniruby -ve 'foo = 1; p({ foo: })'
ruby 3.1.0dev (2021-09-24T13:56:38Z master 40a65030e5) [x86_64-darwin20]
{:foo=>1}
```
This PR amends this logic.
And of course, there are implications like circular arguments validation that was missing:
```
$ /bin/cat ../ruby/test.rb
def m(a = { a: })
end
$ bin/ruby-parse --31 ../ruby/test.rb
../ruby/test.rb:1:13: error: circular argument reference a
../ruby/test.rb:1: def m(a = { a: …
```
> - ruby31.y: handle local variables as hash labels with omitted values

- lib/parser/builders/default.rb
- lib/parser/messages.rb
- test/test_parser.rb
This commit tracks upstream commits ruby/ruby@37eb5e7 and ruby/ruby@9f3888d.
Closes #804
> + builder.rb: warn on duplicate hash key literals.

- lib/parser/lexer.rl
- test/test_lexer.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@11ae581.
Completely closes https://github.com/whitequark/parser/issues/800
> + lexer.rl: parse meta-control-hex chars in regexes starting from 3.1

- .github/workflows/test.yml
- lib/parser/current.rb
- https://www.ruby-lang.org/en/news/2021/11/24/ruby-3-0-3-released/
- https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-7-5-released/
- https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-6-9-released/
Bump 3.0 branch from 3.0.2 to 3.0.3
https://github.com/ruby/ruby/compare/v3_0_2...v3_0_3
Bump 2.7 branch from 2.7.4 to 2.7.5
https://github.com/ruby/ruby/compare/v2_7_4...v2_7_5
Bump 2.6 branch from 2.6.8 to 2.6.9
https://github.com/ruby/ruby/compare/v2_6_8...v2_6_9
> * Bump maintenance branches to 3.0.3, 2.7.5, and 2.6.9

- lib/parser/lexer.rl
- test/test_parser.rb
the bug was introduced in [24d2f68](https://github.com/whitequark/parser/commit/24d2f682c56319266602a3b3115e087fd81d667e) and affects only 3.1-dev
Closes https://github.com/whitequark/parser/issues/830
> fix escaping of ctrl- and meta-chars in regexes

- lib/parser/builders/default.rb
- lib/parser/context.rb
- lib/parser/lexer.rl
- lib/parser/messages.rb
- lib/parser/ruby31.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@13a9597.
Closes https://github.com/whitequark/parser/issues/823.
Also I think I've found a bug in MRI implementation. This code is valid on 3.0:
```ruby
def foo a = 1...
2
p a
end
foo
```
It's a method with 1 argument that has a default value `1...2`. Current MRI/master gives an error:
```ruby
../parser/test.rb:1: syntax error, unexpected (..., expecting ';' or '\n'
def foo a = 1...
../parser/test.rb:4: syntax error, unexpected `end', expecting end-of-input
```
... because it treats **all** triple-dot tokens followed by newline between method-name and method-body as "forward argument".
I think I know how to fix it, there's a single flag for "being in a method arguments definition section", right now it's set once at the beginning of arglist …
> + ruby31.y: parse forward argument without parentheses

- doc/AST_FORMAT.md
- lib/parser/builders/default.rb
- lib/parser/messages.rb
- lib/parser/ruby31.y
- lib/parser/static_environment.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@4adb012.
Closes https://github.com/whitequark/parser/issues/826
> + ruby31.y: parse anonymous block argument.

- lib/parser/current.rb
Calling `warn` 3 times is very annoying for warning management tools that define `Warning.warn`, they're seen as 3 distinct warning instead of a single one.
cc @paracycle
> warn_syntax_deviation: call `warn` only once

- lib/parser/lexer/dedenter.rb
- test/test_parser.rb
There was a missing force_encoding call, which caused Unicode
strings to be returned as binary.
The bug was introduced by 61bf873
This fixes #835
> - dedenter.rb: fix an encoding/squiggly heredoc regression

- lib/parser/builders/default.rb
- lib/parser/context.rb
- lib/parser/lexer.rl
- lib/parser/lexer/explanation.rb
- lib/parser/macruby.y
- lib/parser/max_numparam_stack.rb
- lib/parser/ruby18.y
- lib/parser/ruby19.y
- lib/parser/ruby20.y
- lib/parser/ruby21.y
- lib/parser/ruby22.y
- lib/parser/ruby23.y
- lib/parser/ruby24.y
- lib/parser/ruby25.y
- lib/parser/ruby26.y
- lib/parser/ruby27.y
- lib/parser/ruby30.y
- lib/parser/ruby31.y
- lib/parser/rubymotion.y
- test/helper.rb
- test/parse_helper.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@aa7c4c3.
Also there's a change to Context API that caused a massive rewrite in all grammars.
However, it doesn't affect any logic before 3.1, it's mostly a refactoring.
Closes https://github.com/whitequark/parser/issues/837.
> + ruby31.y: accept forward arg without parentheses.

- .github/workflows/test.yml
- lib/parser/current.rb
- lib/parser/version.rb
also updated CI config, [2.6 is the latest supported version](https://www.ruby-lang.org/en/downloads/branches/)
> * parser/current: update for 3.1.0 release.

- lib/parser/runner.rb
- test/test_runner_parse.rb
use - as the filename to read from stdin
this is useful when parsing multiple lines or code containing characters that would otherwise need to be escaped
> + ruby-parse: add ability to read fragment from stdin

- lib/parser/ruby32.y
Closes #845.
The commits in this PR are separated according to upstream https://github.com/ruby/ruby/pull/5540 and https://github.com/ruby/ruby/pull/5545.
> Reuse `p_kwnorest` and `operation` rules

- .github/workflows/test.yml
- lib/parser/current.rb
Ruby 3.1.1 has been released.
https://www.ruby-lang.org/en/news/2022/02/18/ruby-3-1-1-released/
Bump 3.1 branch from 3.1.0 to 3.1.1
https://github.com/ruby/ruby/compare/v3_1_0...v3_1_1
> Bump 3.1 branch to 3.1.1

- lib/parser/ruby32.y
- test/parse_helper.rb
Also, enable testing for 3.2 (that's why we haven't caught this yet).
`p_kwnorest` is resolved into `s(:match_nil_pattern)`, which we can not use in `f_no_kwarg`.
Ref https://github.com/whitequark/parser/commit/820cc04b8d176c6f46ccc9a010c55f6113f4b2a
> Fix using p_kwnorest in f_no_kwarg

- .github/workflows/test.yml
- lib/parser/current.rb
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-1-2-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-0-4-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-6-10-released/
Bump 3.1 branch from 3.1.1 to 3.1.2
https://github.com/ruby/ruby/compare/v3_1_1...v3_1_2
Bump 3.0 branch from 3.0.3 to 3.0.4
https://github.com/ruby/ruby/compare/v3_0_3...v3_0_4
Bump 2.7 branch from 2.7.5 to 2.7.6
https://github.com/ruby/ruby/compare/v2_7_5...v2_7_6
Bump 2.6 branch from 2.6.9 to 2.6.10
https://github.com/ruby/ruby/compare/v2_6_9...v2_6_10
There …
> * Bump maintenance branches to 3.1.2, 3.0.4, 2.7.6, and 2.6.10

- lib/parser/ruby31.y
- lib/parser/ruby32.y
- test/test_parser.rb
> - ruby31.y: fix preparing the state for one-line patterns without braces

- lib/parser/lexer.rl
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@ec35422.
Closes https://github.com/whitequark/parser/issues/857.
> lexer.rl: handle invalid escape sequences in regexes on the Ruby side since 3.2.

- doc/AST_FORMAT.md
- lib/parser/ast/processor.rb
- lib/parser/builders/default.rb
- lib/parser/messages.rb
- lib/parser/meta.rb
- lib/parser/ruby32.y
- lib/parser/static_environment.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@f53dfab.
Closes https://github.com/whitequark/parser/issues/838.
> + ruby32.y: implement forwarded restarg and kwrestarg.

- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@685efac.
I'm not going to break it for old Rubies, if your code relies on this incorrect behaviour of Ruby < 3.2 feel free to send a PR.
Closes https://github.com/whitequark/parser/issues/859.
> add tests for `class/module <keyword> ...` definition.

- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@982cda9.
`parser` has never been affected by this bug, and I'm not going to backport it. However we have no tests for this diagnostic, so this PR adds one.
Closes https://github.com/whitequark/parser/issues/860.
> add test for bare backslash error.

- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@eaeb130.
Ruby < 3.2 had a bug that emitted tNL if there's a newline after hash key in pattern matching like
```ruby
case foo
in a:
0
1
end
```
Before 3.2 it was `in a: 1` pattern, starting from 3.2 it's `in a:` with a multiline body.
Unfortunately unsetting `in_kwarg` in parsers < 3.2 is not enough to handle all cases, tNL must still be emitted in a few cases, for example for command:
```ruby
in a:
p a
```
but not if it's a trivial expression. I think backporting this bug is not worth it, the chance of introduce new bugs is too high. If you know what is a proper fix please don't hesitate to send a PR.
This PR only adds tests for new behaviour that is implemented by all versions of parser.
Closes https://github.com/whitequark/parser/issues/862.
> add tests for newline after hash key in pattern matching.

- lib/parser/ruby32.y
This commit tracks upstream commit ruby/ruby@3541f32.
Closes https://github.com/whitequark/parser/issues/866.
@koic I'm so sorry, I totally missed an empty rule that you left in https://github.com/whitequark/parser/pull/867, that's why you had a conflict 😄 . Sorry again, I should've noticed it during initial review. IIRC Racc doesn't support comments, this is why empty rules have no visual representation.
> * ruby32.y: reuse opt_nl rule.

- lib/parser/ruby32.y
This commit tracks upstream commit ruby/ruby@13d3133.
Closes https://github.com/whitequark/parser/issues/868.
> * ruby32.y: reuse nonlocal_var rule.

- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@db0e0da.
This is another piece that have been properly implemented in parser since the very beginning. I'm not going to backport the bug.
Closes https://github.com/whitequark/parser/issues/869.
> add tests for multiple pattern matches in a single body.

- .github/workflows/test.yml
[It's no longer maintained](https://www.ruby-lang.org/en/downloads/branches/)
> remove 2.6 branch from CI matrix

- parser.gemspec
Currently there's an error on CI
```
racc --superclass=Parser::Base lib/parser/ruby18.y -o lib/parser/ruby18.rb --no-line-convert
/home/runner/work/parser/parser/vendor/bundle/ruby/3.2.0+3/gems/racc-1.4.15/lib/racc/statetransitiontable.rb:224:in `initialize': unknown regexp option: n (ArgumentError)
Regexp.compile(map, 'n')
^^^^^^^^
from /home/runner/work/parser/parser/vendor/bundle/ruby/3.2.0+3/gems/racc-1.4/lib/racc/statetransitiontable.rb:224:in `compile'
```
> bump racc to 1.6.0

- test/test_parser.rb
TruffleRuby throws a RegexpError with a different message and so assertion fails:
```ruby
-{:message=>"invalid Unicode escape: /foo-\\u-bar/"}
+{:message=>"invalid Unicode escape"}
```
> disable failing test on TruffleRuby

- .github/workflows/test.yml
- lib/parser/current.rb
- test/test_parser.rb
These Rubies have been released.
- https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-1-3-released/
- https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-0-5-released/
- https://www.ruby-lang.org/en/news/2022/11/24/ruby-2-7-7-released/
Bump 3.1 branch from 3.1.2 to 3.1.3
https://github.com/ruby/ruby/compare/v3_1_2...v3_1_3
3 commits have been backported.
The following backport is for testing only, just like #880.
- https://github.com/ruby/ruby/commit/163947f4dc031bb5e619ae64ad4a6a02f8885717
The following two seem to have no corresponding commits in the parser gem for porting.
- https://github.com/ruby/ruby/commit/ffd3d83ea8ccf111061a0f03036e5a093bb03674
- https://github.com/ruby/ruby/commit/750d4dc3aff7c2fef25fe99f1b98327f68734c9a
So, there seems to be no change to the backport syntax. …
> * Bump maintenance branches to 3.1.3, 3.0.5, 2.7.7

- lib/parser/ruby32.y
- test/test_parser.rb
This PR fixes the following Ruby 3.2 parse error when using forwarded argument with restarg.
```console
% ruby-parse -e "def foo(arg, *); bar(arg, *); end"
warning: parser/current is loading parser/ruby32, which recognizes3.2.0-dev-compliant syntax, but you are running 3.2.0.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(fragment:0):1:28: error: unexpected token tRPAREN
(fragment:0):1: def foo(arg, *); bar(arg, *); end
(fragment:0):1:
```
It's valid syntax in Ruby 3.2.
```console
% ruby -vce "def foo(arg, *); bar(arg, *); end"
ruby 3.2.0dev (2022-12-06T02:18:59Z master 80bd9c64aa) [x86_64-darwin19]
Syntax OK
```
It seems that #874's follow-up to the following was insufficient:
https://github.com/ruby/ruby/commit/f53dfab
> - ruby32.y: fix a parse error when using forwarded argument with restarg

- lib/parser/ruby32.y
- test/test_parser.rb
Closes #891.
This commit tracks upstream commit https://github.com/ruby/ruby/commit/764da87.
> + ruby32.y: Allow optional newlines before closing parenthesis

- .gitignore
- .yardopts
- Rakefile
- lib/parser.rb
- lib/parser/lexer.rl
* F0 generates a much smaller Parser::Lexer#advance method which is much better for JITs.
* See https://github.com/whitequark/parser/issues/871
> + lexer.rl: use Ragel -F0 on non-CRuby

- lib/parser/lexer.rl
- lib/parser/source/buffer.rb
- lib/parser/source/range.rb
While optimizing rubocop, I identified that `parser` creates ~100Mb of unneeded `Range` objects while checking just 660 ruby files.
Additionally, made 2 more tiny changes which were producing 1-2% of execution and made them a little faster. 
See https://github.com/rubocop/rubocop/pull/11300 for more details.
> Reduce the number of allocated Ranges

- lib/parser/lexer.rl
See #871 for longer discussion about the size of the `advance` method and the problems it causes for JIT-enabled runtimes.
This PR is a start at "outlining" (as opposed to inlining) repetitive code blocks from the `advance` method by moving them into utility methods. Each commit details the change made plus the reduction in the F1 `advance` instruction count on JRuby 9.4.
My process for outlining, for anyone that wishes to reproduce it:
* Use the [flay](https://github.com/seattlerb/flay) gem to analyze the code, looking for duplicate sections of code.
* Example the findings, ignoring tiny items (simple ivar assignments for example) and blocks of code that have state transitions or multiple "out" variables.
* Outline as much of the remaining duplicate code blocks as possible.
At the time …
> Code size reduction for advance method

- lib/parser/lexer.rl
* This gives big compilation size and time benefit, because the local variables of Lexer#advance are no longer captured by those blocks (even if unused due to Ruby semantics and `Proc#binding`).
* See https://github.com/whitequark/parser/issues/871#issuecomment-1362218586
> Move blocks outside Lexer#advance

- .github/workflows/test.yml
- lib/parser/current.rb
:wave: Trying to add full-release (non-dev) Ruby 3.2.0 support. Based the implementation on https://github.com/whitequark/parser/commit/2f3ce7c57fa72996c28648a5ba8af5f787987fad.
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
Inspired by seeing the following message while running `rubocop` with Ruby 3.2.0 targeted.
```
❯ bundle exec rubocop
warning: parser/current is loading parser/ruby32, which recognizes 3.2.0-dev-compliant syntax, but you are running 3.2.0.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Inspecting 1086 files
.......................................................................................................................................................................................................................... …
```
> Add full-release Ruby 3.2.0 support

- .gitignore
- Rakefile
- lib/parser.rb
- lib/parser/lexer-strings.rl
- lib/parser/lexer.rl
WIP, but there's something to share.
In this PR I've extracted everything related to strings to sub-lexer (`lexer-strings.rl`).  Code in this branch doesn't handle all cases yet, but it is able to lex most string literals and it is able to parse `test_parser.rb`. As I understand it doesn't change anything:
```
$ truffleruby --engine.TraceCompilation --experimental-options -Ilib -rparser/current -rbenchmark -e 'code=File.read("test/test_lexer.rb"); 300.times { p Benchmark.realtime { Parser::CurrentRuby.parse(code) } }' |& grep -E 'Lexer#advance|^[0-9]'
7.519174168002792
5.833842421066947
[engine] opt done     Parser::Lexer#advance                                       |AST 10982|Time 5694(2469+3225)ms|Tier 2|Inlined   0Y 119N|IR 34651/68777|CodeSize 279227|Addr 0x128100000|Src …
```
> * lexer.rl: extract strings lexing to lexer-strings.rl

- .github/workflows/test.yml
- lib/parser/current.rb
Ruby 3.2.1 has been released:
https://www.ruby-lang.org/en/news/2023/02/08/ruby-3-2-1-released/
Bump 3.2 branch from 3.2.0 to 3.2.1:
https://github.com/ruby/ruby/compare/v3_2_0...v3_2_1
> * Bump maintenance branches to 3.2.1

- lib/parser/ast/node.rb
This PR is fix broken link to ast gem documentation.
`ERR_TOO_MANY_REDIRECTS` is raised when accessing [link](http://rdoc.info/gems/ast).
> Fix broken link to ast gem documentation

- lib/parser/builders/default.rb
- test/test_parser.rb
> - builders/default: allow forwarded_kwrestarg with additional kwargs

- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@ddd62fa.
Closes https://github.com/whitequark/parser/issues/885.
No changes to grammar, backporting test just to track it in the future.
> * add tests for kwopt+kwrest arguments and forwarded_kwrestarg.

- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@2581de1.
Closes https://github.com/whitequark/parser/issues/895 and https://github.com/whitequark/parser/issues/888.
There are no changes to grammar, it's a backport of tests.
> * backport tests for mixed usage of anonymous kwarg/kwrestarg and forwarded-arguments

- .github/workflows/test.yml
- lib/parser/current.rb
These Rubies have been released.
- https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-2-2-released/
- https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-1-4-released/
- https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-0-6-released/
- https://www.ruby-lang.org/en/news/2023/03/30/ruby-2-7-8-released/
Bump 3.2 branch from 3.2.1 to 3.2.2
https://github.com/ruby/ruby/compare/v3_2_1...v3_2_2
There seems to be no change to syntax.
Bump 3.1 branch from 3.1.3 to 3.1.4
https://github.com/ruby/ruby/compare/v3_1_3...v3_1_4
There seems to be no change to syntax.
Bump 3.0 branch from 3.0.5 to 3.0.6
https://github.com/ruby/ruby/compare/v3_0_5...v3_0_6
There seems to be no change to syntax.
Bump 2.7 branch from 2.7.7 to 2.7.8
https://github.com/ruby/ruby/compare/v2_7_7...v2_7_8
There seems to be no …
> * Bump maintenance branches to 3.2.2, 3.1.4, 3.0.6, and 2.7.8

- lib/parser/builders/default.rb
- Replaces O(n^2) processing loop with a set. I benchmarked parsing a file with a single 5000 key hash to test this change's performance. Before:
**Before**
```sh
$ hyperfine --warmup 3 'bin/ruby-parse hash_bench.rb'
Benchmark 1: bin/ruby-parse hash_bench.rb
Time (mean ± σ):      2.678 s ±  0.029 s    [User: 2.613 s, System: 0.061 s]
Range (min … max):    2.636 s …  2.738 s    10 runs
```
**After**
```sh
$ hyperfine --warmup 3 'bin/ruby-parse hash_bench.rb'
Benchmark 1: bin/ruby-parse hash_bench.rb
Time (mean ± σ):     421.3 ms ±   4.1 ms    [User: 366.9 ms, System: 49.9 ms]
Range (min … max):   414.8 ms … 426.1 ms    10 runs
```
- See #918
> Optimize duplicate hash key warning

- Gemfile
- parser.gemspec
Follow up https://github.com/ruby/ruby/pull/7877.
Ruby 3.3.0dev is set to promote Racc to a bundled gem. Therefore, this PR adds Racc to runtime dependencies to prevents the following error in RuboCop:
```console
bundle exec rake internal_investigation
rake aborted!
LoadError: cannot load such file -- racc/parser
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/bundle/gems/parser-3.2.2.1/lib/parser.rb:12:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require' …
```
> * Add Racc to runtime dependencies

- Gemfile
Racc 1.7.1 has been released:
https://github.com/ruby/racc/releases/tag/v1.7.1
> * bump Racc to 1.7.1

- lib/parser/builders/default.rb
- test/test_parser.rb
This PR resolves https://github.com/rubocop/rubocop/issues/12198.
```console
$ ruby-parse -e 'if foo..; end'
Failed on: (fragment:0)
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1676:
in `check_condition': undefined method `type' for nil (NoMethodError)
case cond.type
^^^^^
from /Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1707:
in `check_condition'
from /Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/parser-3.2.2.3/lib/parser/builders/default.rb:1275:
in `condition'
```
I'm not sure if there's any significance to using the flip-flop syntax with `nil`, but by using beginless or endless ranges and explicitly specifying `nil`, the following …
> Fix an error for flip-flop with beginless or endless ranges

- README.md
Unfortunately, whitequark's amazing blog has been down since early 2022 as far as I can tell. These blog posts are great resources still for understanding parts of this gem, so I've replaced the broken blog links in the README with the most recent working Internet Archive links.
> Replace whitequark blog links with archive URLs

- Gemfile
Racc 1.7.3 has been released and this PR bumps Racc to 1.7.3.
https://github.com/ruby/racc/releases/tag/v1.7.3
`racc` is specified in the gemspec, it might be possible to remove the `racc` dependency from the Gemfile, although a specific version is still being specified, maintaining previous practices.
> * Bump Racc to 1.7.3

- lib/parser/lexer/literal.rb
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/917
> * literal.rb: match heredoc identifier from end of line

- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/921.
We already reject duplicate variable in pattern-matching like `0 => [a, *a]` and bugs are not back-ported to previous versions of parser, so this PR only includes tests.
> add tests for duplicate variable name check with p_rest

- lib/parser/ruby33.y
Closes https://github.com/whitequark/parser/issues/923.
This is a Ripper-only change + minor refactoring. Here's a test code from the commit:
```ruby
p %w(
w
w w )
```
Ruby 3.2.2:
```sh
$ ruby -v test.rb
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]
["w", "w", "w"]
```
Ruby 3.3.0:
```sh
$ ruby -v test.rb
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
["w", "w", "w"]
```
> * ruby33.y: extract words_sep

- lib/parser/lexer.rl
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/926
> * lexer.rl: treat numparams as locals

- lib/parser/ruby33.y
Closes https://github.com/whitequark/parser/issues/931.
Error recovery is a nice-to-have feature that doesn't have to match MRI 1-to-1, if you want to improve it without sacrificing readability/similarity with parse.y feel free to send a PR.
This PR is only about replicating derivations.
> * ruby33.y: extract string_dend

- lib/parser/ruby33.y
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/933
> + ruby33.y: parse qualified const with brace block as a method call

- lib/parser/ruby33.y
- test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/934
> + ruby33.y: allow semicolon in parenthesis at the first argument of command call

- lib/parser/builders/default.rb
- lib/parser/messages.rb
- lib/parser/ruby33.y
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@bd04676.
Closes https://github.com/whitequark/parser/issues/935
> + builder.rb: reject multi-char gvar names starting with 0

- lib/parser/ruby33.y
This commit tracks upstream commit ruby/ruby@b557855.
Closes https://github.com/whitequark/parser/issues/936.
> + ruby33.y: properly restore in_defined flag, extract begin_defined rule

- README.md
This commit tracks upstream commit ruby/ruby@e1250a5.
This MRI change is an evil twin of "void value expression" checks. If you want to give it a try feel free to send PR. I'm not the one designing Ruby but IMO it should be a runtime check.
This PR simply admits and documents incompatibility with MRI.
Closes https://github.com/whitequark/parser/issues/940
> document running no "syntax checks for block exits" (added first in MRI 3.3.0)

- lib/parser/ruby33.y
This commit tracks upstream commit ruby/ruby@3b05238.
Closes https://github.com/whitequark/parser/issues/951.
Racc doesn't have access to a result of a `p_assoc` rule in the last mid-rule of the diff (probably because of a lookahead?) and so it can't read `$ctxt.in_kwarg`. If that's true for Lrama then it's a very nasty bug that I don't see exactly how to reproduce :(. It could be something like this:
```ruby
def foo a: case 1; in 1; then 1; end, b:
p 42
end
```
that gets rejected (this particular snippet is accepted by MRI which is correct). It could even be a UB if generated code reads uninitialised memory and transmutes it to `ctxt` (then it becomes a heisenbug) but I hope Ruby CI runs ASAN for all of its tests.
> + ruby33.y: extract p_assoc and p_in rules

- lib/parser/ruby33.y
This commit tracks upstream commit ruby/ruby@fe74674.
Closes https://github.com/whitequark/parser/issues/955.
> + ruby33.y: accept expr_value in sclass definition.

- lib/parser/builders/default.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@a607d62.
Closes https://github.com/whitequark/parser/issues/956.
> + builder.rb: extract named captures only from static regexes.

- lib/parser/builders/default.rb
- lib/parser/messages.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@ae76c8a.
Closes https://github.com/whitequark/parser/issues/957.
> + builder.rb: warn `it` in a block with no ordinary params.

- lib/parser/ruby33.y
This commit tracks upstream commit ruby/ruby@11c2aa0.
Closes https://github.com/whitequark/parser/issues/959
> + ruby33.y: extract arg_splat rule.

- parser.gemspec
This gem has used String#delete_suffix which was introduced at Ruby 2.5. https://github.com/whitequark/parser/blob/95d26953ebe823211845fb84cb93c18cd501f561/lib/parser/lexer/literal.rb#L250
Ref. https://github.com/ruby/ruby/blob/ruby_2_5/NEWS
So, even Ruby 2.0 can be installed now, however it will not work.
> Fix incorrect required_ruby_version

- lib/parser/lexer/literal.rb
- parser.gemspec
This is an alternative approach to the changes in #985. The Parser gem may be required to operate across as many Ruby versions as possible. The use of `delete_suffix` starts from Parser version 3.3.0.0. Therefore, by replacing `delete_suffix` with `sub`, and releasing Parser 3.3.0.1, supporting Ruby 2.0 would be feasible.
> - Supports Ruby 2.0+ runtime

- lib/parser/lexer/literal.rb
- test/test_lexer.rb
I've found #986 regression in the following RuboCop CI matrix: https://github.com/rubocop/rubocop/actions/runs/7437077900/job/20234293932?pr=12598
So, #986 was not a sufficient fix. This PR fixes an error when using heredoc with non-word delimiters:
```ruby
<<~'+'
foo
+
```
The following repro test have been newly added:
```console
$ bundle exec ruby -Itest test/test_lexer.rb
(snip)
1) Error:
TestLexer#test_heredoc_plus_character:
RegexpError: target of repeat operator is not specified: /+\z/
/Users/koic/src/github.com/whitequark/parser/lib/parser/lexer/literal.rb:250:in `delimiter?'
/Users/koic/src/github.com/whitequark/parser/lib/parser/lexer/literal.rb:138:in `nest_and_try_closing'
/Users/koic/src/github.com/whitequark/parser/lib/parser/lexer-strings.rb:4165:in `advance' …
```
> - Fix an error when using heredoc with non-word delimiters

- lib/parser/lexer/literal.rb
- test/test_parser.rb
- test/test_runner_rewrite.rb
Closes https://github.com/whitequark/parser/issues/989.
The bug is not related to blocks specifically but example from the report can also be parsed now:
```
$ /bin/cat test.rb
foo do
<<~DESC
bar
DESC
end
$ bin/ruby-parse --33 test.rb
(block
(send nil :foo)
(args)
(str "bar\n"))
```
> - lexer.rl: accept tabs before closing heredoc delimiter

- .github/workflows/test.yml
- lib/parser/current.rb
- lib/parser/lexer.rl
- test/test_parser.rb
Ruby 3.2.3 has been released:
https://www.ruby-lang.org/en/news/2024/01/18/ruby-3-2-3-released/
Bump 3.2 branch from 3.2.2 to 3.2.3
https://github.com/ruby/ruby/compare/v3_2_2...v3_2_3
Thas PR is backport #926 to Ruby 3.2 branch.
cf. https://github.com/ruby/ruby/commit/465eb7418d7ed91f5f0c75da77765c7f5ef8354f
> * Bump 3.2 branch to 3.2.3

- lib/parser.rb
- lib/parser/source/buffer.rb
- lib/parser/unknown_encoding_in_magic_comment_error.rb
- test/test_encoding.rb
Closes #998
Let me know if I should tweak the docs for the exception in some way.
I also know that this library still targets Ruby 2.0. CI only seems to test against somewhat recent versions. I used the old begin/end syntax since I know that omitting the begin was added somewhere between but other than that I haven't tested on older versions.
> Raise a more specific error when encountering an unknown magic comment encoding

- lib/parser/ast/processor.rb
This PR uses `AST::Processor::Mixin` instead of deprecated `AST::Processor` API:
```ruby
#
```
https://github.com/whitequark/ast/blob/v2.4.2/lib/ast/processor.rb#L2-L7
There is an imcompatibility where the inheritance no longer includes `AST::Processor`, but the impact is expected to be negligible.
> Use `AST::Processor::Mixin` instead of deprecated `AST::Processor`

- lib/parser/source/tree_rewriter/action.rb
Few sentence and formatting corrections
The first section shows up on RubyDoc as a code block:
https://www.rubydoc.info/gems/parser/Parser/Source/TreeRewriter/Action
> `action.rb` doc fixes

- lib/parser/ruby33.y
- lib/parser/ruby34.y
- lib/parser/static_environment.rb
- test/test_parser.rb
This commit tracks upstream commit ruby/ruby@596db9c.
Closes https://github.com/whitequark/parser/issues/963.
Unfortunately there are 0 tests for `anonymous <PARAM> parameter is also used within block` error message in the ruby/ruby repo.
<details>
<summary>A small script to verify this behaviour</summary>
```sh
set -x
$RUN 'def b(&) ->(&) {c(&)} end'
$RUN 'def b(*) ->(*) {c(*)} end'
$RUN 'def b(a, *) ->(*) {c(1, *)} end'
$RUN 'def b(*) ->(a, *) {c(*)} end'
$RUN 'def b(**) ->(**) {c(**)} end'
$RUN 'def b(k:, **) ->(**) {c(k: 1, **)} end'
$RUN 'def b(**) ->(k:, **) {c(**)} end'
echo
$RUN 'def b(&) ->(&) {c()} end'
$RUN 'def b(*) ->(*) {c()} end'
$RUN 'def b(**) ->(**) {c()} end'
echo
$RUN 'def b(&) ->() {c(&)} end'
$RUN 'def b(*) ->() {c(*)} end'
$RUN 'def b(a, *) ->() {c(1, *)} end'
$RUN …
```
> + ruby{33,34}.y: allow blocks inherit anonymous args.

- .github/workflows/test.yml
- lib/parser/current.rb
Ruby 3.1.6 has been released:
https://www.ruby-lang.org/en/news/2024/05/29/ruby-3-1-6-released/
Bump 3.1 branch from 3.1.5 to 3.1.6:
https://github.com/ruby/ruby/compare/v3_1_5...v3_1_6
> * Bump 3.1 branch to 3.1.6

- Gemfile
Racc 1.8.0 has been released and this PR bumps Racc to 1.8.0: https://github.com/ruby/racc/releases/tag/v1.8.0
> * Bump Racc to 1.8.0

- .github/workflows/test.yml
- lib/parser/current.rb
Ruby 3.3.3 has been released:
https://www.ruby-lang.org/en/news/2024/06/12/ruby-3-3-3-released/
Bump 3.3 branch from 3.3.2 to 3.3.3:
https://github.com/ruby/ruby/compare/v3_3_2...v3_3_3
> * Bump maintenance branches to 3.3.3

- .github/workflows/test.yml
- lib/parser/current.rb
Ruby 3.3.4 has been released:
https://www.ruby-lang.org/en/news/2024/07/09/ruby-3-3-4-released/
Bump 3.3 branch from 3.3.3 to 3.3.4:
https://github.com/ruby/ruby/compare/v3_3_3...v3_3_4
> * Bump maintenance branches to 3.3.4

- lib/parser/source/buffer.rb
Starting with Ruby 3.4, there is a gradual plan to freeze strings: https://bugs.ruby-lang.org/issues/20205#note-35
This PR suppresses the following Ruby 3.4's warning:
```console
/Users/koic/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/parser-3.3.4.0/lib/parser/source/buffer.rb:97:
warning: literal string will be frozen in the future
```
> Suppress Ruby 3.4's warning

- Gemfile
Racc 1.8.1 has been released and this PR bumps Racc to 1.8.1:
https://github.com/ruby/racc/releases/tag/v1.8.1
> * Bump Racc to 1.8.1

- lib/parser/source/buffer.rb
Follow up https://github.com/whitequark/parser/pull/1031#issuecomment-2257868932 and reverts #1028.
This PR fixes the following error:
```console
$ ci/run_rubocop_specs
(snip)
==> Failed Examples
rspec  # RuboCop::Cop::Lint::PercentStringArray with binary encoded source adds an offense and corrects when tokens contain quotes
rspec  # RuboCop::Cop::Lint::PercentStringArray with binary encoded source accepts if tokens contain no quotes
rspec './spec/rubocop/cop/layout/end_of_line_spec.rb[1:3:6:2]' # RuboCop::Cop::Layout::EndOfLine when EnforcedStyle is lf and the default external encoding is US_ASCII can inspect non-UTF-8 encoded source with proper encoding comment
rspec './spec/rubocop/cop/layout/end_of_line_spec.rb[1:3:5:2]' # RuboCop::Cop::Layout::EndOfLine when EnforcedStyle is lf and …
```
> - Fix errros in the ascii specs of RuboCop

- lib/parser/runner.rb
Ruby wants to bundle it: https://github.com/ruby/ruby/pull/11492, which means that the next ruby release will warn and the one after that will error, unless it is added to the gemspec. Usage is trivial and can simply be inlined.
The benchmark gem does it like this for 14 years already so I don't imagine compatibility problems with older ruby versions: https://github.com/ruby/benchmark/blame/0383673a9089d6a74a73ef37c67d5afc15d66d71/lib/benchmark.rb#L277-L287
Test with `bin/ruby-parse lib/parser/ruby34.rb --bench`.
> Remove `benchmark` dependency from the runner

- .github/workflows/test.yml
- lib/parser/current.rb
Ruby 3.3.5 has been released:
https://www.ruby-lang.org/en/news/2024/09/03/3-3-5-released/
Bump 3.3 branch from 3.3.4 to 3.3.5:
https://github.com/ruby/ruby/compare/v3_3_4...v3_3_5
> * Bump maintenance branches to 3.3.5

- .github/workflows/test.yml
- lib/parser/current.rb
Closes #1043.
Ruby 3.2.6 has been released:
https://www.ruby-lang.org/en/news/2024/10/30/ruby-3-2-6-released/
Bump 3.2 branch from 3.2.5 to 3.2.6:
https://github.com/ruby/ruby/compare/v3_2_5...v3_2_6
> * Bump maintenance branches to 3.2.6

- .github/workflows/test.yml
- lib/parser/current.rb
Ruby 3.3.6 has been released:
https://www.ruby-lang.org/en/news/2024/11/05/ruby-3-3-6-released/
Bump 3.3 branch from 3.3.5 to 3.3.6:
https://github.com/ruby/ruby/compare/v3_3_5...v3_3_6
> * Bump maintenance branches to 3.3.6

- lib/parser/runner.rb
- test/test_runner_parse.rb
It's just checking that the path ends with `.rb`, which can happen with folders.
For example: https://github.com/chef/chef/tree/1ea245124173f803af628abd70adc87baa70a873/knife/spec/data/client.d_02/foo.rb
> - Fix `ruby-parse` with a folder ending in `.rb`

- lib/parser/context.rb
- lib/parser/ruby34.y
- test/test_parser.rb
This tracks upstream commit https://github.com/ruby/ruby/commit/e642ddf7ae86e306674559ae745823fdbf56ea10
Closes #1029.
Note that `in_class` is now unused for 3.4 as far as I can tell. Ruby uses it in `begin_definition` helper but I don't think there's something equivalent with ragel here, or I just don't know about it. Kept around to keep it closer to upstream.
Tested against https://github.com/eliotsykes/real-world-rails and https://github.com/jeromedalbert/real-world-ruby-apps, got no unexpected syntax errors.
> + ruby34.y: reject `return` in singleton class

- test/parse_helper.rb
- test/test_parser.rb
It's easy to invert version subtraction and then not test anything
Not like I almost did that myself or anything 🙃
> * assert that version-specific checks actually run against at least one version

- .github/workflows/test.yml
- lib/parser/current.rb
No grammar changes: https://github.com/ruby/ruby/compare/v3_4_0...v3_4_1
Closes https://github.com/whitequark/parser/issues/1056.
> * bump 3.4 branch, remove 3.0 from CI (EOL)

- .github/workflows/test.yml
- lib/parser/current.rb
Reverts whitequark/parser#1057
My bad, 3.4 has NOT been fully backported, don't know what I was thinking of.
> Revert "* bump 3.4 branch, remove 3.0 from CI (EOL)"

- .github/workflows/test.yml
- lib/parser/current.rb
Ruby 3.3.7 has been released:
https://www.ruby-lang.org/en/news/2025/01/15/ruby-3-3-7-released/
Bump 3.3 branch from 3.3.6 to 3.3.7:
https://github.com/ruby/ruby/compare/v3_3_6...v3_3_7
> * Bump maintenance branches to 3.3.7

- .github/workflows/test.yml
Github has updated its images and so `ubuntu-latest` is now `ubuntu-24.04`.
[There's no pre-built JRuby 9.2 for `ubuntu-24.04`](https://github.com/ruby/ruby-builder/releases/tag/toolcache), so this PR bumps it to 9.4.
Additionally, MRI 3.0 is EOL.
> update CI config (bump JRuby version, drop MRI 3.0 branch)

- lib/parser/builders/default.rb
- test/test_parser.rb
A constant always start in uppercase but a local will not always start with lowercase. `_foo` and `💎` are both valid local variables.
> - builder.rb: fix hash value omission considering some local vars as constants

- README.md
Because of https://github.com/whitequark/parser/issues/1046. It will look like this:
> [!WARNING]  
> The `parser` gem can only correctly parse Ruby code up to and including Ruby 3.3. For Ruby 3.4 and later, please use the [Prism translation parser](https://github.com/ruby/prism/blob/main/docs/parser_translation.md) instead.
> Starting in Ruby 3.4, Prism is the parser used in Ruby itself and can produces AST that is identical to the output of `parser`. If you only need to parse Ruby 3.3 (or greater), also consider using the native Prism AST.
> See this [GitHub issue](https://github.com/whitequark/parser/issues/1046) for more details.
I think this makes sense?
> Document the current state of the project in the readme

- lib/parser/meta.rb
It's a bit akward: rubocop and rubocop-ast use this list to generate visitors and node type predicates. Since they both use this, it doesn't make much sense to add this handling in rubocop I think.
On the other hand, adding this to prism doesn't really work since the parser there is lazily loaded, and by rubocop as well since users may just use older ruby versions. Prism itself has no dependecy on parser to eagerly add to this list.
I think adding this to parser is ok, and is also the simplest solution to the problem. The list can (and does) contain entries that are parser-version specific, this just extends that policy a bit farther than it used to be.
cc @koic
> + add prism-specific node types

- README.md
- doc/AST_FORMAT.md
- doc/PRISM_TRANSLATION.md
Ref https://github.com/whitequark/parser/pull/1071#issuecomment-2736283700
cc @bbatsov
I'm not a good technical writer so this can probably use some grease here and there. I think I've got the main points that can come up. I also added `itblock` to the ast docs and marked it was prism-only.
This only focuses on the translation layer, not on using prism standalone.
> Document parser/prism migration path

- .github/workflows/test.yml
- lib/parser/current.rb
These Rubies have been released.
- https://www.ruby-lang.org/en/news/2025/03/26/ruby-3-2-8-released/
- https://www.ruby-lang.org/en/news/2025/03/26/ruby-3-1-7-released/
Bump 3.2 branch from 3.2.7 to 3.2.8
https://github.com/ruby/ruby/compare/v3_2_7...v3_2_8
There seems to be no change to syntax.
Bump 3.1 branch from 3.1.6 to 3.1.7
https://github.com/ruby/ruby/compare/v3_1_6...v3_1_7
There seems to be no change to syntax.
> * Bump maintenance branches to 3.2.8 and 3.1.7

- lib/parser/ruby27.y
- lib/parser/ruby30.y
- lib/parser/ruby31.y
- lib/parser/ruby32.y
- lib/parser/ruby33.y
- lib/parser/ruby34.y
- test/test_parser.rb
The following is how different versions behave:
```rb
case 0; in _1; end
1.then { 1 in _1 }
case 0; in ^_1; end
1.then { 1 in ^_1 }
```
`@builder.accessible` makes the numparam visible to the environment, so it must be called first
> Numbered parameters are valid for pattern matching pinning

- lib/parser/builders/default.rb
- lib/parser/lexer.rl
User input can contain arbitrary regexes.
Something like `Parser::CurrentRuby.parse("/[\177\01\1778]/")` shows a warning:
> character class has duplicated range: /[\x7f\x01\x7f8]/
I'm interested in getting the warning count in the RuboCop test suite down and since it has a few regex cops there are quite a few warnings of that kind as well. They are unactionable, RuboCop instead emulates these warnings by inspecting the ast parsing the regexp with the `regexp_parser` gem.
-------
Also noticed the same for floats:
`Parser::CurrentRuby.parse("9.9999e999")`
> Float 9.9999e999 out of range
> Supress warnings during parsing

- lib/parser/builders/default.rb
- test/test_parser.rb
Closes #1004
Upstream commit https://github.com/ruby/ruby/commit/a850cd1a87bef738c40d9c550fb8823699083f2e is specific to 3.3, previous versions already did not allow this.
See https://bugs.ruby-lang.org/issues/20392 for a bit more info.
But since the super node has has a different shape, it behaved unexpectedly in earlier ruby versions already.
It allowed forwarding with zero and one arguments and failed for more. Now it correctly rejects as invalid syntax, except in Ruby 3.3, that fix has not been backported.
> - builder.rb: correctly handle `...` forwarding to super with explicit block

- lib/parser/builders/default.rb
- test/test_parser.rb
Noticed while looking into https://github.com/whitequark/parser/issues/1002
> - builder.rb: emit `kwargs` node for `indexasgn` when opted in

- lib/parser/base.rb
- lib/parser/current.rb
Documentation changes:
* Add YARD docs for `Parser::CurrentRuby`:
* Document the transition for users seeking Ruby 3.4 support
* Allow IDE tools like Solargraph to understand the invocation and results from Parser::Current.parse() to provide auto-completion and type checking
* Add type info for `Parser::Base#version`
> * YARD docs for Parser::CurrentRuby and Parser::Base#version

- .github/workflows/test.yml
- lib/parser/current.rb
Ruby 3.3.8 has been released:
https://www.ruby-lang.org/en/news/2025/04/09/ruby-3-3-8-released/
Bump 3.3 branch from 3.3.7 to 3.3.8
https://github.com/ruby/ruby/compare/v3_3_7...v3_3_8
There seems to be no change to syntax.
> * Bump maintenance branches to 3.3.8

- .github/workflows/test.yml
- lib/parser/current.rb
Ruby 3.3.9 has been released:
https://www.ruby-lang.org/en/news/2025/07/24/ruby-3-3-9-released/
Bump 3.3 branch from 3.3.8 to 3.3.9:
https://github.com/ruby/ruby/compare/v3_3_8...v3_3_9
There seems to be no change to syntax.
> * Bump maintenance branches to 3.3.9
