README.md, lib/parser/runner.rb, lib/parser/runner/ruby_parse.rb, lib/parser/runner/ruby_rewrite.rb, parser.gemspec
=> Use optparse instead of slop

README.md
=> Remove a note about the 2.2 support

lib/parser/lexer.rl, test/test_lexer.rb
Please have a look and see if you want any of these changes.
=> More tweaking on the lexer

lib/parser/ruby23.y, test/test_parser.rb
See https://github.com/ruby/ruby/commit/d311b7d0eb1e973c8d143f03e66ab72588f57a2a.
=> 2.3: optional superclass rule

README.md
Pretty much supported by all browsers at this point, and just look way better.
=> Move badges from PNG to SVG

lib/parser/lexer.rl, lib/parser/lexer/literal.rb, lib/parser/source/range.rb, test/test_source_range.rb
Just picked everything which should be uncontroversial out of #249. Hopefully these can be merged more quickly.
=> Some tweaks

lib/parser/source/rewriter.rb, lib/parser/source/rewriter/action.rb, test/test_source_rewriter.rb
For https://github.com/whitequark/parser/pull/259#issuecomment-184514530
=> Add Source::Rewriter APIs for multiple insertions at the same position

lib/parser/runner.rb
I guess somewhat went wrong with bbf01ba1f7be660cc11fb43b8c733dbd9b1cbd73.
=> runner.rb fixes

lib/parser/lexer/literal.rb
Required for https://github.com/opal/opal/pull/1465
=> Remove string mutations in Parser::Lexer::Literal.

lib/parser/source/rewriter.rb
Discovered w/Ruby verbose mode
=> Remove unused variable: begin_pos

doc/AST_FORMAT.md, lib/parser/ast/processor.rb, lib/parser/builders/default.rb, lib/parser/macruby.y, lib/parser/ruby18.y, lib/parser/ruby19.y, lib/parser/ruby20.y, lib/parser/ruby21.y, lib/parser/ruby22.y, lib/parser/ruby23.y, lib/parser/ruby24.y, lib/parser/rubymotion.y, test/test_parser.rb
=> Introduce (procarg0) node for tCOMMA in "|a,|".

doc/AST_FORMAT.md
Same as #348 but better. Fixes other issues, e.g.
* * *
=> Fix AST format documentation format

doc/AST_FORMAT.md
Remove Ruby_parser's output from AST doc
=> Remove Ruby_parser's output from AST doc [ci-skip]

CHANGELOG.md, Rakefile
It tries to fix the PR: https://github.com/whitequark/parser/pull/372
=> Change log rake task should not generate tag sections w/o commits

lib/parser/source/buffer.rb, lib/parser/source/comment.rb, lib/parser/source/comment/associator.rb
I searched similar point of  #389 .
=> use String#start_with? instead of Regexp match

lib/parser/source/rewriter.rb, test/test_source_rewriter.rb
Reverts whitequark/parser#399.
See whitequark/parser#403.
=> Revert "Change relative order of insert_after_multi and insert_before_multi"

lib/parser/source/range.rb
Yay for #406 
Here's a follow-up.
=> Range#with: optimize for Ruby 2+

lib/parser/base.rb, lib/parser/builders/default.rb, lib/parser/lexer.rl, lib/parser/lexer/literal.rb, lib/parser/ruby18.y, lib/parser/runner.rb, lib/parser/source/buffer.rb, test/helper.rb, test/test_encoding.rb, test/test_lexer.rb, test/test_parser.rb, test/test_source_buffer.rb
=> Remove Ruby 1.x remnants

lib/parser.rb, lib/parser/base.rb, lib/parser/builders/default.rb, lib/parser/context.rb, lib/parser/macruby.y, lib/parser/messages.rb, lib/parser/ruby18.y, lib/parser/ruby19.y, lib/parser/ruby20.y, lib/parser/ruby21.y, lib/parser/ruby22.y, lib/parser/ruby23.y, lib/parser/ruby24.y, lib/parser/ruby25.y, lib/parser/rubymotion.y, lib/parser/source/tree_rewriter/action.rb, test/parse_helper.rb, test/test_parser.rb, test/test_runner_rewrite.rb
Closes #396 
ruby/ruby@8c15f40
@whitequark If this solution is good enough, please, let me know if you need more tests (of if some tests are redundant).
=> Prohibit return in class/module body except for singleton class.

lib/parser/lexer.rl, test/test_lexer.rb
=> Parse '1if' as '1 if'.

lib/parser/ast/node.rb, lib/parser/runner/ruby_parse.rb, parser.gemspec
Hi there, 
I'm interested in being able to read a Ruby AST from JavaScript. I imagined that others might be interested in cross-language machine-readable access to the Ruby AST as well. 
I have yet to add docs & tests to this PR, but wanted to put it up now as a strawdog for feedback.
I believe that this PR title, once squashed, should pass your commit guidelines; please let me know if there's anything else expected. 
How does this look?
=> + Add option to emit JSON S-Expressions.

lib/parser/ruby25.y
Closes https://github.com/whitequark/parser/issues/436.
ruby/ruby@762d23c
=> Extract begin_block rule.

lib/parser/ruby25.y
Closes #437
ruby/ruby@508533f.
=> Extract expr_value_do rule.

lib/parser/ruby26.y, test/test_parser.rb
Upstream commit: ruby/ruby@140512d.
Closes https://github.com/whitequark/parser/issues/477
=> Raise a syntax error on 'else' without 'rescue'.

lib/parser/lexer.rl, lib/parser/ruby24.y, lib/parser/ruby25.y, lib/parser/ruby26.y, test/test_parser.rb
Upstream commit ruby/ruby@9c5d90b.
Closes https://github.com/whitequark/parser/issues/481 and https://github.com/whitequark/parser/issues/483
=> Use only CMDARG/COND _PUSH/POP for cmdarg/cond management.

lib/parser/builders/default.rb, lib/parser/context.rb, lib/parser/macruby.y, lib/parser/ruby18.y, lib/parser/ruby19.y, lib/parser/ruby20.y, lib/parser/ruby21.y, lib/parser/ruby22.y, lib/parser/ruby23.y, lib/parser/ruby24.y, lib/parser/ruby25.y, lib/parser/ruby26.y, lib/parser/rubymotion.y, test/test_parser.rb
Closes https://github.com/whitequark/parser/issues/490
=> Allow class definition in the method definition if it there's a sclass between them.

doc/AST_FORMAT.md
=> Fix a wrong indentation in the AST_FORMAT.md

.travis.yml, lib/parser/tree_rewriter.rb, parser.gemspec
The `#rewrite` method takes at least two arguments: A buffer and an AST.
=> Fix example in TreeRewriter documentation

.travis.yml, lib/parser/current.rb
Closes https://github.com/whitequark/parser/issues/553
=> Bump version to 2.6.1.

doc/AST_FORMAT.md
Closes https://github.com/whitequark/parser/issues/532
=> Fix documentation of the string with interpolation.

lib/parser/macruby.y, lib/parser/ruby18.y, lib/parser/ruby19.y, lib/parser/ruby20.y, lib/parser/ruby21.y, lib/parser/ruby22.y, lib/parser/ruby23.y, lib/parser/ruby24.y, lib/parser/ruby25.y, lib/parser/ruby26.y, lib/parser/ruby27.y, lib/parser/rubymotion.y, test/test_parser.rb
`else_` is nil in `def m; else; end`, but `else_t` is there.
=> Detect and warn about empty else

lib/parser/lexer.rl, test/parse_helper.rb, test/test_parser.rb
=> - lexer.rl: fix paren_nest for curly braces

doc/AST_FORMAT.md, lib/parser/builders/default.rb, test/test_parser.rb
See https://github.com/whitequark/parser/pull/659#issuecomment-601489391
=> - builder.rb: fix constant_pattern source map

lib/parser/source/tree_rewriter.rb
I noticed some documentation that I forgot to update (years ago).
Thanks
=> Fix TreeRewriter#transaction [DOC]

test/test_current.rb
=> - test_current.rb: 2.8 -> 3.0

lib/parser/base.rb, lib/parser/context.rb, lib/parser/current_arg_stack.rb, lib/parser/lexer.rl, lib/parser/max_numparam_stack.rb, lib/parser/ruby27.y, lib/parser/ruby30.y, lib/parser/static_environment.rb, lib/parser/variables_stack.rb, test/parse_helper.rb
I've found a few bugs that would be revealed once https://github.com/ruby/ruby/pull/3956 is merged
=> add more state checks to the tests suite

.github/workflows/test.yml, lib/parser/current.rb
Also updated CI config to include 3.0.0
=> * current.rb: bump default branch to parser/ruby30.

lib/parser/ruby32.y
=> + ruby32.y: reduce p_args with p_rest

.github/workflows/test.yml
=> Upgrade Github Actions test workflow

lib/parser/lexer.rl
=> * lexer.rl: extract `extend_string_escaped` to a separate method

lib/parser.rb
=> Use -F1 on JRuby

lib/parser/lexer.rl
Required for https://github.com/whitequark/parser/pull/899.
cc @headius
=> * lexer.rl: change `p` variable to `@p`.

README.md
This PR updates parsing Ruby versions in README.md.
=> Update parsing Ruby versions in README.md

lib/parser/ruby33.y
Closes https://github.com/whitequark/parser/issues/907
=> * ruby33.y: extract {endless_command,endless_arg} rules

lib/parser/ruby33.y
This commit tracks upstream commit ruby/ruby@7e80f0b.
Closes https://github.com/whitequark/parser/issues/953.
=> + ruby33.y: extract p_in_kwarg

.github/workflows/test.yml, lib/parser/current.rb
and bump versions in CI config
=> * current.rb: mark 3.3 branch as stable

lib/parser/ruby34.y, test/test_parser.rb
and a change to a few tests to fix syntax highlighting.
No functional changes.
=> a few fixes to fully integrate 3.4 grammar

.github/workflows/test.yml, lib/parser/current.rb
=> * parser/current: add -dev prefix to 3.4 branch
